### ISSUE TITLE
论@DREAMWORLDVOID 的代码质量问题

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorld#10]
``` C++
// DataKit.cpp : 定义 DLL 应用程序的导出函数。
//

#include "stdafx.h"
#include "DataKit.h"
#include <stdio.h>
#include <sstream>

// 这是导出变量的一个示例
DATAKIT_API int nDataKit=0;

// 这是导出函数的一个示例。
DATAKIT_API int fnDataKit(void)
{
    return 42;
}

// 这是已导出类的构造函数。
// 有关类定义的信息，请参阅 DataKit.h
CDataKit::CDataKit()
{
    return;
}
```

问题一：不用UTF-8；
问题二：Microsoft的示例代码你都不删；
问题三：你加入一个DLL都不通知一声；
17行代码，3个错，平均5行多代码1个错，不合格儿。

``` C++
    void object::read(std::fstream & file)
    {
    }

    void object::write(std::fstream & file)
    {
    }

    object::~object()
    {
    }
```

代码没写完，一个错儿。

``` C++
    typedef std::map<unsigned long long, object*> _sd;
```

_sd意义不明，并且没有注释，一个错儿。

``` C++
        if (i != ((_st*)val)->end())
        {
            ((_st*)val)->erase(i->first);
        }

        if (!res||(res->type!=DK_LIST)) {
                addsub(key.substr(0, found), DK_LIST);
                ((cl_list*)((*this)[key.substr(0, found)]))->createdir(key.substr(found + 2));
        }
```

两段相隔8行的代码，一个是Allman/ANSI Bracket Style，一个是Java Bracket Style，一个错儿。

``` C++
    class DATAKIT_API cl_file : public cl_list {
        std::wstring fname;
    public:
        void open(std::wstring name);
        void save();
    };
```

不把public成员写前面，一个错儿。

**Comment by ascchrvalstr** [comment]
@DREAMWORLDVOID 这就是我revert并取消你权限的真正原因。

**Comment by taxerap** [comment]
“儿”，exciting

**Comment by DWVoid** [comment]
而且我并不希望你们来维护这个组件的代码（下次改完在以后我是不是要加CopyRight说明？）

发件人: noreply@github.com [mailto:noreply@github.com] 代表 Bruce Dai
发送时间: 2016年4月10日 22:52
收件人: Infinideastudio/NEWorld NEWorld@noreply.github.com
抄送: DREAMWORLDVOID ys_37677@126.com
主题: Re: [Infinideastudio/NEWorld] 论@DREAMWORLDVOID 的代码质量问题 (#10)

@DREAMWORLDVOID https://github.com/DREAMWORLDVOID  这就是我revert并取消你权限的真正原因。

**Comment by DWVoid** [comment]
准确来说这个不是为NW项目开发的代码，而是为另外一个项目开发的数据管理代码，还没来得及写完

发件人: bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com [mailto:bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com] 代表 Bruce Dai
发送时间: 2016年4月10日 22:48
收件人: Infinideastudio/NEWorld NEWorld@noreply.github.com
主题: [Infinideastudio/NEWorld] 论@DREAMWORLDVOID 的代码质量问题 (#10)

`// DataKit.cpp : 定义 DLL 应用程序的导出函数。
//

#include "stdafx.h"
#include "DataKit.h"
#include 
#include 

// 这是导出变量的一个示例
DATAKIT_API int nDataKit=0;

// 这是导出函数的一个示例。
DATAKIT_API int fnDataKit(void)
{
return 42;
}

// 这是已导出类的构造函数。
// 有关类定义的信息，请参阅 DataKit.h
CDataKit::CDataKit()
{
return;
}`
问题一：不用UTF-8；
问题二：Microsoft的示例代码你都不删；
问题三：你加入一个DLL都不通知一声；
17行代码，3个错，平均5行多代码1个错，不合格儿。

` void object::read(std::fstream & file)
{
}

void object::write(std::fstream & file)
{
}

object::~object()
{
}`

代码没写完，一个错儿。

typedef std::map<unsigned long long, object*> _sd;
_sd意义不明，并且没有注释，一个错儿。

if (i != ((_st_)val)->end())
{
((_st_)val)->erase(i->first);
}
if (!res||(res->type!=DK_LIST)) {
addsub(key.substr(0, found), DK_LIST);
((cl_list_)((_this)[key.substr(0, found)]))->createdir(key.substr(found + 2));
}
两段相隔8行的代码，一个是Allman/ANSI Bracket Style，一个是Java Bracket Style，一个错儿。

class DATAKIT_API cl_file : public cl_list {
std::wstring fname;
public:
void open(std::wstring name);
void save();
};
不把public成员写前面，一个错儿。

**Comment by DWVoid** [comment]
刚刚清理完成，仍然不是Unicode
http://dreamworldvoid.github.io/DataKit

**Comment by ascchrvalstr** [comment]
那你写完再commit啊。。。
Repo里全是写一半的代码就是因为这个。。。

**Comment by ascchrvalstr** [comment]
那么多成熟的数据存储库你都不用，偏要自己造轮子
写出来的代码全是不能看
单独一个datakit，你偏要用动态库
那一大堆兼容问题你还懂啊

**Comment by ascchrvalstr** [comment]
你自己弄出来的问题，还要我来纠正
Git合作协议说过了加入新库要说明

**Comment by DWVoid** [comment]
也不完全是轮子，我准备是对sqlite进行封装

发自我的 iPad

**Comment by ghost** [comment]
@DREAMWORLDVOID 既然这部分代码并不是NEWorld的代码，是外部的库，建议你把这部分代码移动到git submodule里面，不要加入到NEWorld的主Git库里面。

**Comment by ghost** [comment]
@ascchrvalstr 烦劳勤查email邮箱，我和你用email联络。

**Comment by ascchrvalstr** [comment]
@DLaboratory OK

**Comment by ascchrvalstr** [comment]
@DREAMWORLDVOID 你又弄出来一个问题——你加入sqlite都不和我们说，严重违反了团队合作条例。
另外，你不经过任何思考就把README.md等文件给改变成你fork时候的样子，也严重违反了团队合作条例。
而且你merge以后就不管conflict了，也严重违反了团队合作条例。
因此，施以严厉处罚。
(1)取消write权限；
(2)revert掉更改。

**Comment by ghost** [comment]
`git reset --hard c5a77f0`
DONE

**Comment by DWVoid** [comment]
@ascchrvalstr 有吗，我记得刚才已经手动合并了所有conflict

**Comment by ghost** [comment]
我觉得....这个merge搞错了....错的很严重...

在 16/4/16 下午7:36, 刘予顺 写道:

**Comment by ghost** [comment]
@DREAMWORLDVOID 时间线错了....还是在命令行手动merge吧...

**Comment by DWVoid** [comment]
@DLaboratory 话说Unix的命令行我真的不熟。。。

**Comment by harrynull** [comment]
@DREAMWORLDVOID 你为啥退群，对于交流极其不便

**Comment by DWVoid** [comment]
不是我退的，之前给我老妈删了

**Comment by taxerap** [comment]
被告已有悔改之意，是否close？

**Comment by DWVoid** [comment]
@DLaboratory 什么时候库和代码都整理好了告诉我一声，我得重新fork，之前的fork已经废了

**Comment by DWVoid** [comment]
@Infinideastudio/neworld-team @Infinideastudio/cppgroup 话说要重新获得push权限要满足什么条件？

**Comment by ascchrvalstr** [comment]
@DREAMWORLDVOID [代码规范](https://github.com/Infinideastudio/NEWorld/blob/0.5.0/doc/regulations.md)

**Comment by DWVoid** [comment]
如何评定？

发自我的 iPad

**Comment by ascchrvalstr** [comment]
@DREAMWORLDVOID 由我和@DLaboratory 钦点
已恢复write权限，但issue暂时不关

**Comment by ascchrvalstr** [comment]
@DREAMWORLDVOID `src/client/Grafics.h`结尾为什么没有回车，请小心你的write权限（再取消一次就是永久取消）

**Comment by harrynull** [comment]
@DREAMWORLDVOID 注意你的命名规范
变量名、函数名小驼峰，类名、命名空间名大驼峰

**Comment by DWVoid** [comment]
@abc612008 明白。不过小驼峰实在看着不舒服（发句牢骚，这样等于逼着我在每个变量名前加'member'，否则不太美观）

**Comment by bridgekat** [comment]
@DREAMWORLDVOID 小驼峰确实有点不舒服，忍一忍就是了233

**Comment by harrynull** [comment]
@DREAMWORLDVOID 尽快修改命名，另外，你的Object类重名了。请把你的代码放到GUI/UI文件夹里。

**Comment by DWVoid** [comment]
你能否帮忙改一下，最近有点忙

**Comment by harrynull** [comment]
@DREAMWORLDVOID  好

**Comment by DWVoid** [comment]
@ascchrvalstr 为何又一次不经通知就取消权限

**Comment by DWVoid** [comment]
@abc612008 @qiaozhanrong 

> 当出现恶意地上传二进制文件/大文件等在本文件中注明“施以严厉处罚”的行为，由全体开发者讨论决定处罚方案。

我到底违反哪一条了，你们两个评评理

**Comment by harrynull** [comment]
@DREAMWORLDVOID 好像是因为你用的旧版本的textrenderer……我也不太清楚，dyt也没有公开讨论，建议你加群交流。

**Comment by DWVoid** [comment]
@abc612008 我前面都声明了“只是作为参考”，到最后会全盘翻掉重来

**Comment by DWVoid** [comment]
条例里面自己写明要“全体讨论”，结果每次都是一个人自己决定

**Comment by DWVoid** [comment]
算了 @abc612008 帮我在Infinideas下面新开一个Repo 命名为UI，我把UI部分分出去

**Comment by harrynull** [comment]
@DREAMWORLDVOID 好的[GameUI](https://github.com/Infinideastudio/GameUI)

**Comment by bridgekat** [comment]
@DREAMWORLDVOID DYT貌似有点不同意宽松版规范，他一直想把规范改得更严格

**Comment by ascchrvalstr** [comment]
我同意了
