### ISSUE TITLE
Game starting failed!

### ISSUE THREAD

**Issue by charlesdong** [Infinideastudio/NEWorld#101]
I downloaded the game from AppVeyor a few days ago. Then I executed NEWorldLauncher.exe and entered "client". And it said:
...
2017-00-10 10:49:28[launcher][warning]Failed to load v41. Error code:126
2017-00-10 10:49:28[launcher][fatal]Assertion failed!
	Source :	c:\neworld\src\engine\maintenance/nwdebug.h
	At Line :	31
	Function :	AssertFunc

2017-00-10 10:49:28[launcher][fatal]At line 100 in "c:\neworld\src\engine\nwstdlib/nwlibrary.h", function Library::getFunc
	Source :	c:\neworld\src\engine\maintenance/nwdebug.h
	At Line :	32
	Function :	AssertFunc

**Comment by huayurensheng** [comment]
This is an exercise, the author is too young, do not expect more

**Comment by charlesdong** [comment]
Well, I've understood recently by reading the code. "v41" should be a name of a DLL, but it doesn't exist. So maybe that's because the current version is still in development.

**Comment by WenceyWang** [comment]
Sorry about this, this game is still in development and most of our developer are students who can't reply issues in time. Sorry.

**Comment by WenceyWang** [comment]
And this issue make us know that it's nessary to use English in document and chat.

**Comment by jacky8399** [comment]
DO mind that NEWorld is still in rapid development. This is **NOT** the final product so there may be bugs and crashes.

Also, if you can code, you may as well help the developers out, instead of saying that they are "too young" and "don't expect more from NEWorld". Your comment contributes nothing to this issue.

**Comment by charlesdong** [comment]
WenceyWang: Actually, I wrote this in English because this website (github.com) is in English, the issue #99 (explosionPower shouldn't be stored in NWblocktype) is also in English (actually most of the issues are in Chinese), and finally I'd like to practise my English.
