### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by palsza53332** [Infinideastudio/NEWorld#103]
qiaozhanrong
i am palsza53332.

PS:are you writing the game already???

ppps:doyou need one to write???

**Comment by palsza53332** [comment]
i can write most of c++,i learned cpp first.but i dont kown anything about OpenGL.

**Comment by DWVoid** [comment]
If you are from China，please use Simplified Chinese to communicate with us.
Thank you for your cooperation!

**Comment by jacky8399** [comment]
Keep in mind that issues should not be used to communicate with other developers. Please use other means of communication, like Tencent QQ.

**Comment by harrynull** [comment]
We do have another project which still need some more developers. You may join us as long as you have good skill at C++. Contact me at abc612008at126.com if you are interested in it.
