### ISSUE TITLE
怎么自己写plugin？

### ISSUE THREAD

**Issue by charlesdong** [Infinideastudio/NEWorld#106]
Repository里没有提供任何关于自己写plugin的资料

**Comment by WenceyWang** [comment]
据我对这个项目的了解似乎他们还没重构出个样子，你要是不嫌弃就接着这个烂摊子想想办法吧。

**Comment by charlesdong** [comment]
我就是想知道以下plugin是怎么写的，要哪些头文件、lib等

**Comment by harrynull** [comment]
可以参考一下Main，整个游戏逻辑都是一个大插件

**Comment by charlesdong** [comment]
Main是什么？main()函数吗？还是一个类？

**Comment by harrynull** [comment]
插件的名字，内容是游戏逻辑

**Comment by DWVoid** [comment]
确实没有成型的框架，而且对于一个C++项目搞一个C-API框架确实也是一件头疼事。不过目前master分支应qiaozhanrong的想法基本处于暂停状态，建议你去咨询一下他关于这个项目的想法
