### ISSUE TITLE
Is this repository still being maintained?

### ISSUE THREAD

**Issue by DXGatech** [Infinideastudio/NEWorld#108]
This is a really sophisticated project that has implemented most mandatory features for a voxel game, although artificial intelligence is not included.
The last commit was submitted months ago; it's really a pity if this project is no longer maintained.

**Comment by harrynull** [comment]
No, all main developers have already stopped maintaining this project as far as I know, and there is no plan to restart it yet. While I am not sure if the project will be picked up someday, you are still welcome to contribute or use the code as long as you follow the license.

**Comment by jacky8399** [comment]
Please check the `readme` before creating an issue.
This repository is **NO LONGER** being actively maintained.

**Comment by DXGatech** [comment]
the eventual submission is preceded with the last edit of the readme file
that was my last hope
heh
plus, it might be readme instead of the readme 💯

**Comment by DWVoid** [comment]
Well, i'm planning to resume the  development, but before doing that, some serious plannng, researching and preparing need to be done.

**Comment by DXGatech** [comment]
Frankly speaking, a voxel game would take less time to make and be much easier to maintain and expand if you plan to use a game engine that supports basic transformations of geometric objects.
I've created a voxel game's primitive that encompasses basic artificial intelligence units, biome generation, infinite terrain, advanced block manipulation( like stretching and rotating the blocks during runtime ) and **mobile support** using unreal engine. I plan to put it on github, so check out my repositories for progress if you're interested.
You can even advance further( like, smoothing the terrain by applying the marching cubes algorithm, which is very time-consuming and lacks mobile support )

**Comment by DWVoid** [comment]
Well, the key point is that we don't really plan to use a game engine.

**Comment by harrynull** [comment]
Using a game engine does make things easier, but in the meantime, it also limits the ability to optimize the game specifically for voxel games. Also, the original intention for making the game is to learn how a game works. By making the game from scratch, we can learn the underneath parts of a game.

**Comment by DXGatech** [comment]
You can't find a good way to distribute your work( mobile and console support, for instance ) and have to spend a HUGE amount of time to deal with a ton of trivial problems if you don't have a sophisticated framework available.
"it also limits the ability to optimise the game specifically for voxel games"
That's not a problem if you use unreal engine OR unity, since procedural contents that are interconnected to the OpenGL apis and independent of the mesh generation cores are available in both engines. With the help of these features, it's SUPER simple to construct a voxel framework within a mesh engine.
If you're really interested and want to know more about this specific field, you can check out several UE4 frameworks that have great potential for voxel games.
RuntimeMeshComponent( don't get spooked by its name ), procedural mesh components, brick games, unrealvoxel and, last but not least, my own UE4 framework :D
Cheers, hope that someday you guys will be able to revive your project.

**Comment by DWVoid** [comment]
Well, we DO use some simple frameworks in our current codebase, such as SDL, glew(or glfw and glew, which is used in previous releases, whatever) to deal with a ton a trivial problems and made serveral simple abstractions above these frameworks. Since no advanced physical emulation , fancy graphic, or complicated animations was needed in this game at that time, it was a great success. A lot of effort has been put into optimizing memory usage, mesh generation, which enabled this game to run much more faster than mincraft[1.7, at that time] and to offer a view distance of 32*16 blocks at 30fps(which is hard to achieve by simply doing some simple hacking on game engines, I guess). This has made the codebase almost impossible to maintain. We tried to rewrite the entire game, but failed. 
Currently we are designing the game's new architecture. If anyone have any good suggestions about this, please tell us. (not limited to graphic frameworks)(:D

**Comment by DXGatech** [comment]
No, the frameworks you're currently using do not provide enough benefits.
1. No multi-platform support, as I mentioned above.
2. No dynamic material editors provided, still too trivial and hard to maintain.
3. About the fps, have you guys implemented basic artificial intelligence units? What about advanced graphical effects like volumetric fogs and so on? 30fps is average level of my UE4 voxel project after I implemented the ai units, and I'm using an old 2013 OS X desktop. You'll encounter countless difficulties if you plan to advance further.
And you can recreate EVERY feature of neworld in unreal within a month. My project took less than 3 weeks to have all the stuffs that a basic survival game needs.

**Comment by Miigon** [comment]
NEWorld is more like a researching project,rather than a game project.

**Comment by DXGatech** [comment]
That's probably the reason why it's much less productive
