### ISSUE TITLE
[征求意见]关于用sqlite3统一代替现有NEWorld的所有数据储存模块

### ISSUE THREAD

**Issue by DWVoid** [Infinideastudio/NEWorld#11]
RT，各位怎么看？

**Comment by dtcxzyw** [comment]
如果好用且允许用的话干嘛不用呢？

**Comment by HydroH** [comment]
个人觉得数据库形式不太适合存储这类形式的数据……

**Comment by rand-fly** [comment]
+1  我还是强烈建议用rapidjson

在 2016年4月12日，19:37，Iodizon Aleph <notifications@github.com<mailto:notifications@github.com>> 写道：

个人觉得数据库形式不太适合存储这类形式的数据……

―

**Comment by DWVoid** [comment]
如果你说的是层状结构的话用一种特定方式可以解决，而且数据库的优点在于不用全部载入内存

发自我的 iPad

**Comment by DWVoid** [comment]
我觉得不会有人玩出2TB的存档，所以sqlite就足够了

发自我的 iPad

**Comment by ascchrvalstr** [comment]
随便一个库就可以满足需求了。。。
我不同意SQLite

**Comment by DWVoid** [comment]
@ascchrvalstr 其实目的是为了代替最初设计用来储存存档的NNN，那个随便用个库好像有点问题，毕竟都是二进制数据

**Comment by ghost** [comment]
个人建议LevelDB，性能比SQLite3快得不知道高到哪里去了。

**Comment by DWVoid** [comment]
@DLaboratory 看过LevelDB了，据使用方式来看确实更为适合，不过没有索引，编辑有时可能需要遍历操作，比较耗时

**Comment by DWVoid** [comment]
有一个问题：LevelDB不支持UWP，对Windows的支持也不好，因为它执行的是POSIX的标准

发自我的 iPad

**Comment by ghost** [comment]
@DREAMWORLDVOID 什么叫做不支持UWP？我不了解UWP，什么是支持UWP？LevelDB也好，SQLite也好，都是C/C++语言编写的数据库程序，和UWP会有什么关系？请介绍一下。
只要对LevelDB的源码进行一定的修改，就能在WIndows上编译和运行。执行POSIX标准也是最好的，我正苦于研究怎么让NEWorld在UNIX-like平台上编译运行。NEWorld的依赖项Netycat就是Windows only的库，需要一个跨平台的替代品。从今以后给NEWorld添加新的dependency，必须要考虑跨平台问题，不能再找Windows only的库了。

**Comment by rand-fly** [comment]
你们就是喜欢造轮子，NNN和Netycat这些都是没必要的（貌似我在黑SSS
（为何乱码之前不是可以么。。

**Comment by ghost** [comment]
@renfei147 全都是乱码，GitHub不要用邮件回复中文。

**Comment by ghost** [comment]
@renfei147 诶，是GFW的问题，挂了VPN之后就正常了。不翻墙，邮件回复的内容全都是乱码。

**Comment by rand-fly** [comment]
@DLaboratory 那是因为我刚才改好了。。这个应该是因为我把邮件回复里原来的引用删掉了，然后邮件就自动改了编码

**Comment by ghost** [comment]
我发一个邮件试验一下。

在 16/4/14 下午10:22, renfei147 写道:

**Comment by DWVoid** [comment]
@DLaboratory  UWP=Universal Windows Platform 完完全全依赖.Net运行，而sqlite几乎支持所有平台，在兼容性方面远超LevelDB

**Comment by DWVoid** [comment]
@DLaboratory 虽然曾经有人为LevelDB制作了适用于UWP的CLI类库，但是在v1.1以后停止了维护，也就是说无法适用于目前v1.8的版本，总不见得自己再写一遍。。。

**Comment by ghost** [comment]
@DREAMWORLDVOID 为什么要涉及到.NET Framework(UWP)？这是一个C/C++的项目，
设计目标是跨平台。

在 16/4/15 上午9:37, DREAMWORLDVOID 写道:

**Comment by DWVoid** [comment]
@DLaboratory 目标就是跨所有平台。。。因为UWP不支持POSIX的I/O操作，所以所有的io端口都要修改，还不如用现成的sqlite

**Comment by ghost** [comment]
@DREAMWORLDVOID 我疑惑的就是，NEWorld和UWP有什么关系？为什么要考虑UWP？

在 16/4/15 下午2:22, 刘予顺 写道:

**Comment by ascchrvalstr** [comment]
NEWorld以后又不准备弄到应用商店里面去，完全没必要用UWP，而且NEWorld是要准备跨平台的，做成UWP就要面对微软的一大堆让人云里雾里的API了。。。
