### ISSUE TITLE
游戏无法运行

### ISSUE THREAD

**Issue by wetstreet** [Infinideastudio/NEWorld#118]
控制台显示OpenGL Error 1282，屏幕为一片蓝，是我缺了什么文件吗

**Comment by harrynull** [comment]
能确认编译的是 refactor 分支的最新 commit 并且 module 也编译了吗。建议把完整的控制台log发上来以便分析。

此外，你还需要手动安装材质包等素材文件。
[Assets.zip](https://github.com/Infinideastudio/NEWorld/files/4201277/Assets.zip)
请在下载以上文件然后解压到二进制文件同目录后重试。

**Comment by wetstreet** [comment]
我是下载AppVeyor上的最新Release包，然后点击NEWorld.exe运行的，没有clone项目，也没有编译，这种情况下是否还要手动安装材质包呢？我看Product目录下已经有Assets了。完整控制台log可以从哪个文件获取到吗（如果有保存到文件里的话）

**Comment by harrynull** [comment]
目前 AppVeyor 上的目录结构有些问题，需要你手动做以下操作：
1. 将 `Product\Assets` 和 `Product\Modules` 文件夹复制到 `Product\Release` 里（即和.exe文件同目录）。
2. 再将 `Product\Release\Modules\Release\Main.nwModule` 复制到 `Product\Release\Modules\Main.nwModule`

**Comment by wetstreet** [comment]
可以运行了，感谢
