### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [Infinideastudio/NEWorld#119]
Would you like to [wrap any pointer data members](https://github.com/Infinideastudio/NEWorld/blob/4c7dcf1cdc8b297f40dc3407638deb0ca9d00800/Shells/GUI/Source/renderer/vertexarray.h#L51 "Update candidate: VertexArray class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by DWVoid** [comment]
This class is purely legacy code. There is an intension to remove this class in favor of better implementations with newer GL APIs. Thank you for your suggestion anyway.
