### ISSUE TITLE
Remove unnecessary checks for API handles

### ISSUE THREAD

**Issue by elfring** [Infinideastudio/NEWorld#120]
[An extra check is not needed for a zero API handle](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDeleteProgram.xhtml "Description from the OpenGL reference") in functions like the following.
* [Renderer::configShader](https://github.com/Infinideastudio/NEWorld/blob/4c7dcf1cdc8b297f40dc3407638deb0ca9d00800/Shells/GUI/Source/renderer/renderer.cpp#L110 "Renderer::configShader function")
* [Shader](https://github.com/Infinideastudio/NEWorld/blob/4c7dcf1cdc8b297f40dc3407638deb0ca9d00800/Shells/GUI/Source/renderer/renderer.cpp#L51 "Destructor for Shader")

**Comment by DWVoid** [comment]
There will be no change regarding the first issue. This check for zero handles is reserved for further functionality expansion in the future to ensure the previous program is properly released before a new one is installed. For the second one, I will check against the standard to ensure the behavior is correct if the constructor fails. Thanks for your time anyway.

**Comment by DWVoid** [comment]
And if you are proposing such changes in the future, it would be nice if you could provide a solution via 'Pull requests' or send a patch to us so that we can verify the feasibility of the proposal quickly. Thanks
