### ISSUE TITLE
最新版NEWorld还无法编译？

### ISSUE THREAD

**Issue by harrynull** [Infinideastudio/NEWorld#14]
许多编译时、运行时错误

**Comment by harrynull** [comment]
@DLaboratory @ascchrvalstr

**Comment by harrynull** [comment]
而且字体删掉了应该提供一个下载链接啊

**Comment by harrynull** [comment]
我自己修复了

**Comment by ghost** [comment]
请贴出错误信息，我这里无法编译。

在 2016-04-16 11:04:45，"Null" notifications@github.com 写道：

许多编译时、运行时错误

**Comment by harrynull** [comment]
已经修改好了，顺便重构了些代码

在 2016-04-16 11:21:16，"D Laboratory" notifications@github.com 写道：
请贴出错误信息，我这里无法编译。

在 2016-04-16 11:04:45，"Null" notifications@github.com 写道：

许多编译时、运行时错误

**Comment by ghost** [comment]
稍等片刻。

在 16/4/16 上午11:05, Null 写道:
