### ISSUE TITLE
FPS异常低

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorld#15]
如题，经过某些人一番乱搞以后，FPS再也没有原来的六七百那么高了，某些时候甚至只有个位数

**Comment by harrynull** [comment]
Release模式吗

**Comment by ghost** [comment]
用Profile看一看Hotspot在哪里。

在 16/4/16 下午2:16, Bruce Dai 写道:

**Comment by DLaboratory** [comment]
126的邮箱太蛋疼了，只要我在一定时间内用邮件客户端通过SMTP方式发送一定量的邮件，就认为我是一个垃圾邮件发送者，冻结我账户的SMTP通信几个小时。然后，abc612008在14:18发了“Release模式吗”，我在14:27才收到....网易吃枣药丸。

**Comment by DLaboratory** [comment]
谁能简要介绍一下GameView.cpp的功能？算法和常数写的都比较粗放，有优化余地。

**Comment by ascchrvalstr** [comment]
@abc612008 无论哪个模式

**Comment by ascchrvalstr** [comment]
@DLaboratory 用新浪邮箱

**Comment by DLaboratory** [comment]
@ascchrvalstr 有QQ吗？我想要请教一些GameView.cpp的写法。

**Comment by ascchrvalstr** [comment]
@DLaboratory 以前的NEWorld.cpp，@DREAMWORLDVOID 把它里面的内容抽出来弄成一个GameView

**Comment by ascchrvalstr** [comment]
@DLaboratory 1841364214

**Comment by harrynull** [comment]
我这里profile的时候fps200~
hotspot较为均匀，主要是Grender以及其中的glDrawArrays和文字渲染，暂时没看到明显的可优化点
@ascchrvalstr @DLaboratory

**Comment by ghost** [comment]
@abc612008 烦劳您用邮件将Hotspot列表发给我。
dlaboratory@126.com
我进行详细的静态分析。

**Comment by dtcxzyw** [comment]
我特效全最高FPS有1800

**Comment by DWVoid** [comment]
@ascchrvalstr 突然的fps骤降是由于存档有大量小文件，而生成的detail全部会被储存（目前是树），再次加载就会非常慢。 @dtcxzyw 这个你来解决一下

**Comment by dtcxzyw** [comment]
因为rnd并没有唯一性

**Comment by DWVoid** [comment]
@dtcxzyw 让你用perlin你不用

**Comment by dtcxzyw** [comment]
之前没时间改

**Comment by dtcxzyw** [comment]
我晚上试试

**Comment by bridgekat** [comment]
突然减慢是硬盘IO的问题

**Comment by bridgekat** [comment]
【吧

**Comment by bridgekat** [comment]
对对对就是树造成的大量硬盘IO，然后加载的时候很卡

**Comment by DWVoid** [comment]
@qiaozhanrong 所以我准备用数据库了，但是得先merge一大堆conflict。。。

**Comment by dtcxzyw** [comment]
为什么不直接存储方块而是存储修改？

**Comment by DWVoid** [comment]
@dtcxzyw 所以要用数据库啊，否则又要造轮子

**Comment by dtcxzyw** [comment]
行

**Comment by DWVoid** [comment]
@dtcxzyw 我这边还在挂载虚拟机，解决冲突还是VS好，Xcode不行

**Comment by harrynull** [comment]
@DLaboratory 我用的VS自带的profiler，不知道怎么导出

**Comment by ghost** [comment]
@abc612008 就是VS自带的Profiler

**Comment by harrynull** [comment]
@DLaboratory 哦看到了，csv文件？

**Comment by jacky8399** [comment]
→_→我覺得你們一說吧 下一個NEWorld新版本絕對沒有新功能 只有優化
還有的話 為甚麼樹會造成大量IO啊 我覺得你們應該向MCPE看齊 把所有的修改都記錄了 其他就靠地形生成器用種子生成

**Comment by ascchrvalstr** [comment]
FPS低的问题仅仅发生在开启合并面的情况下。

**Comment by bridgekat** [comment]
@ascchrvalstr 并不知道怎么回事

**Comment by bridgekat** [comment]
@DREAMWORLDVOID 为什么要用数据库啊啊啊啊啊啊啊啊

**Comment by bridgekat** [comment]
@dtcxzyw @DREAMWORLDVOID 
用坐标计算出的种子生成随机数来确定哪里有树，然后生成树但是没更改过的区块不保存进硬盘不就是了吗。。。实在不行搞个多区块文件格式啊。。。

**Comment by bridgekat** [comment]
@dtcxzyw 现在是存储修改过的区块中的方块

**Comment by DWVoid** [comment]
本来全球化部分我就打算用数据库（链接进程序要500kb，sqlite312000），数据库在某些方面比我们自己造的轮子可靠多了

发件人: bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com [mailto:bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com] 代表 qiaozhanrong
发送时间: 2016年4月28日 16:40
收件人: Infinideastudio/NEWorld NEWorld@noreply.github.com
抄送: 刘予顺 ys_37677@126.com; Assign assign@noreply.github.com
主题: Re: [Infinideastudio/NEWorld] FPS异常低 (#15)

@ascchrvalstr https://github.com/ascchrvalstr  并不知道怎么回事

**Comment by dtcxzyw** [comment]
然而现在我没有write权限（fork特麻烦而且没人受理pr），而且最近很少再写代码了

**Comment by ascchrvalstr** [comment]
@DREAMWORLDVOID gettext大法好

**Comment by DWVoid** [comment]
文字是脚本，还不是html和json，不爽

**Comment by bridgekat** [comment]
@DREAMWORLDVOID 现在的轮子貌似不会出问题啊

**Comment by DWVoid** [comment]
可这个“轮子”偏偏就是在UNIX上出了问题

发件人: bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com [mailto:bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com] 代表 qiaozhanrong
发送时间: 2016年4月29日 15:45
收件人: Infinideastudio/NEWorld NEWorld@noreply.github.com
抄送: 刘予顺 ys_37677@126.com; Mention mention@noreply.github.com
主题: Re: [Infinideastudio/NEWorld] FPS异常低 (#15)

@DREAMWORLDVOID https://github.com/DREAMWORLDVOID  现在的轮子貌似不会出问题啊

**Comment by bridgekat** [comment]
@DREAMWORLDVOID 编码问题？

**Comment by DWVoid** [comment]
貌似不是编码那么简单

在 2016-04-30 18:58:09，qiaozhanrong notifications@github.com 写道：

@DREAMWORLDVOID 编码问题？

**Comment by harrynull** [comment]
重写中
