### ISSUE TITLE
跨平台改造：OpenAL

### ISSUE THREAD

**Issue by ghost** [Infinideastudio/NEWorld#18]
在Mac OS X上，OpenAL并没有EFX Extension。环境音效无法使用。

**Comment by ghost** [comment]
@SuperSodaSea 中国有一句古话，叫做

> 解铃还需系铃人

**Comment by ghost** [comment]
@dtcxzyw AL的工作就钦点你去完成了。

**Comment by jacky8399** [comment]
中國有一句古話，叫做

> 悶聲發大財

**Comment by ghost** [comment]
@jacky8399 在GitHub上发这个GIF图，就不怕整个网站都被续掉？还是要学习一个啊！

**Comment by xy12423** [comment]
@DLaboratory 
boost::asio大法好！
直接全改成boost::asio或者libuv这类东西不就完了

**Comment by ghost** [comment]
Netycat经过我的改造已经可以在UNIX系统上编译了。

**Comment by jacky8399** [comment]
我今天把所有大陸GitHub用戶都得罪了下！excited！

**Comment by ghost** [comment]
![2016-04-17 6 42 40](https://cloud.githubusercontent.com/assets/5671495/14586492/81fde014-04cc-11e6-8b79-aa10dfaebf56.png)
非常赛艇，今天终于在Mac上把NEWorld运行起来了。虽然界面乱码，而且四个按钮，不管按哪一个都会崩溃 = =

**Comment by ghost** [comment]
![2016-04-17 6 53 56](https://cloud.githubusercontent.com/assets/5671495/14586553/fa1f8eac-04cd-11e6-9789-aedfb91847fc.png)
还是要提高一个啊，总共就四个按钮，按哪一个都能崩溃。

**Comment by ascchrvalstr** [comment]
@DLaboratory 最好废弃已经弃坑的Netycat，改用成熟的boost::asio

**Comment by ghost** [comment]
@ascchrvalstr 我可以接坑啊(笑

**Comment by DWVoid** [comment]
我很抱歉地通知您，原先的lang文件都是CodePage937的，尽管我在执着sqlite3的语言文件是已经修正了这一点，但是你们revert掉了。

**Comment by DWVoid** [comment]
关于按键崩溃的问题，估计是出现了空指针，很有可能和之前比较粗放的代码风格有关。能否把后面的错误输出给我看一下，谢谢。

**Comment by ghost** [comment]
@DREAMWORLDVOID 在`TextRenderer.cpp`中的第91行发生崩溃。

``` C++
void MBToWC(const char* lpcszStr, wchar_t*& lpwszStr, int dwSize)
{
    lpwszStr = (wchar_t*)malloc(dwSize);
    memset(lpwszStr, 0, dwSize);
    int iSize = (MByteToWChar(lpwszStr, lpcszStr, strlen(lpcszStr)) + 1)*sizeof(wchar_t);
    lpwszStr = (wchar_t*)realloc(lpwszStr, iSize); //这里崩溃了
}
```

**Comment by DWVoid** [comment]
先把lang下面的文件转码成UTF－8试试，毕竟OSX只支持这个,有可能是null字符识别错误导致的

**Comment by ghost** [comment]
转成UTF-8之后，也是乱码，只不过乱码长得不一样了。崩溃，依然崩溃。

在 16/4/17 下午8:57, 刘予顺 写道:

**Comment by DWVoid** [comment]
我这边正在尝试编译OS X版。话说你这个移除文件移除一半是蛮让人头疼的，错误一堆一堆出现

**Comment by DWVoid** [comment]
./StdInclude.h:74:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^
1 error generated.
GLProc.cpp
这个如何解决？

**Comment by DWVoid** [comment]
-lvorbis -lvorbisfile 是什么库？我这边找不到

**Comment by ghost** [comment]
我是在命令行手动编译的，你如果不会的话，等我以后写Makefile吧。

在 16/4/17 下午9:09, 刘予顺 写道:

**Comment by DWVoid** [comment]
倒也不是不会，就是库有点难找

**Comment by DLaboratory** [comment]
因为根本就没有vorbis和ogg，需要自己用
```
./configure
make
make check
make install
make clean
```
去www.xiph.org、www.vorbis.com下载。

在 16/4/17 下午9:22, 刘予顺 写道:

**Comment by ghost** [comment]
建议去学习UNIX命令行的那一套理论，和GCC/GDB的那一套理论。把《UNIX环境高级
编程(第三版)》看完。要不然就在Windows上 开发，为了效率和心情，一定要选择
最适合自己的环境。我是因为用了7年的Linux了，上一次用微软的那一套东西已经
是六年之前，所以坚持在 UNIX下开发，微软的那一套evil的理论我已经忘得差不
多了。

**Comment by DWVoid** [comment]
其实也没什么，只不过之前都是用Xcode，刚才才发现库缺的厉害，然后现在满屏都是shell窗口在跑clang

**Comment by ghost** [comment]
和Visual Studio相比，Xcode就像是IE相对于Chrome，图样图森破。UNIX世界下用
UNIX世界的方式，微软世界下用微软世界的方式，西方世界用 西方的那一套媒
体，这是坠吼的。极端不推荐Xcode！去年有一个版本的Xcode会把Git历史搞乱！
而且我还没有备份！

**Comment by DWVoid** [comment]
我算是明白为何昨天会被你们降权限了。。。昨天我操作git用的就是那个Xcode。。。

**Comment by DWVoid** [comment]
刚才在glfw上出问题了，下周有空继续。如果乱码还搞不定我看看改用sqlite能否解决问题

**Comment by ghost** [comment]
@DREAMWORLDVOID 个人存档使用二进制方法存储，游戏数据使用JSON格式存储，这是我的个人经验。

**Comment by ascchrvalstr** [comment]
@DLaboratory 尽量用boost::asio，实在弄不了再用Netycat

**Comment by ghost** [comment]
往NEWorld里面引入Boost这么一个超重量级的库，必须要慎重，应当把这个作为最
后的备选方案，而不是首选方案。如果Netycat还可 以维护，就用Netycat。如果
弃坑了，就选择RakNet、libuv、libevent等轻量级的库。

**Comment by SuperSodaSea** [comment]
@DLaboratory Netycat坑了，以及asio是有非boost版的 http://think-async.com/

**Comment by taxerap** [comment]
其实。。。。OpenAL最初的目的不就是跨平台的么。。。

**Comment by ghost** [comment]
OpenAL是跨平台的不假，但是NEWorld却使用了EAX这种微软系统独有的OpenAL
Extension，在UNIX世界上没法编译。

**Comment by DWVoid** [comment]
@DLaboratory 发现了一个问题

``` C++
void MBToWC(const char* lpcszStr, wchar_t*& lpwszStr, int dwSize)
{
    lpwszStr = (wchar_t*)malloc(dwSize);
    memset(lpwszStr, 0, dwSize);
    int iSize = (MByteToWChar(lpwszStr, lpcszStr, strlen(lpcszStr)) + 1)*sizeof(wchar_t);
    lpwszStr = (wchar_t*)realloc(lpwszStr, iSize);
} MBToWC(s.c_str(), wstr, s.length()+128);
```

这就证明了dwSize不是实际的字节大小，而是字符串长度，而目前的
`malloc(dwSize)`导致定位的内存大小可能不足
既然是c++，建议用`lpwszStr = new wchar_t[dwSize];`修正

**Comment by SuperSodaSea** [comment]
@DLaboratory 以及OpenAL相关代码不是我写的……

**Comment by ascchrvalstr** [comment]
@DLaboratory 正在重构network模块，已经把client的全改成asio了(还没commit)

**Comment by ghost** [comment]
网络模块已经替换为了Asio，目前还剩余OpenAL以及PluginSDK。另外，在Mac上存在鼠标移动不平滑、方块有些时候只显示骨架、键盘输入失灵、GUI界面文本乱码的现象，需要开发人员解决。

**Comment by DWVoid** [comment]
键盘输入是更新方式有问题

发自我的 iPad

**Comment by ascchrvalstr** [comment]
@DLaboratory 09224ddd011d100cf2449c33c2fd3a015aa423cf

**Comment by ascchrvalstr** [comment]
@DLaboratory 建议使用[Maximilian](https://github.com/micknoise/Maximilian)或者其他轻量级音频库代替OpenAL

**Comment by SuperSodaSea** [comment]
@ascchrvalstr 看了一下Maximilian只支持WAV和OGG……

**Comment by jacky8399** [comment]
OGG不好嗎

**Comment by ghost** [comment]
OGG可是自由格式哦
_Free as in freedom_

**Comment by dtcxzyw** [comment]
现在的代码也支持ogg和wav格式，以后还会支持flac

**Comment by SuperSodaSea** [comment]
@jacky8399 @DLaboratory 是自由格式，不过我听说OGG的常用视频编码Theora是捡别人丢下的VP3改的，效果渣的一逼……所以我也有些怀疑常用音频编码Vorbis的质量……

**Comment by SuperSodaSea** [comment]
@dtcxzyw 我们似乎不需要无损音频……（不过FLAC作为无损还是不错的）

**Comment by ghost** [comment]
@SuperSodaSea 你可以用`ffmpeg`转几个ogg试听一下，在同比特率(128kbps)、同采样率(44.1kHz)下，ogg的音质比mp3好，文件大小比mp3还小，

> 这难道不是一支令人可敬的军队吗？

**Comment by ghost** [comment]
@SuperSodaSea 也可以用GoldWave的频谱图看一下，在同比特率(128kbps)、同采样率(44.1kHz)下，ogg还原了很多mp3中丢失的高频细节，文件大小比mp3还小。

**Comment by SuperSodaSea** [comment]
@DLaboratory 难道不应该和aac比较吗？mp3都是很老的东西了（虽然aac也很老）

**Comment by ghost** [comment]
@SuperSodaSea AAC的解码器faac似乎有版权问题

> FFmpeg can support three AAC-LC encoders (aac, libfaac, libfdk_aac) and one HE-AAC(v1/2) encoder (libfdk_aac). The licenses of libfaac and libfdk_aac are not compatible with the GPL, so the GPL does not permit distribution of binaries containing code licensed under these licenses when GPL-licensed code is also included. Therefore these encoders have been designated as "non-free", and you cannot download a pre-built ffmpeg that supports them. This can be resolved by compiling ffmpeg yourself.

**Comment by SuperSodaSea** [comment]
@DLaboratory 这样好像就没得选了（逃

**Comment by jacky8399** [comment]
蛤？MC用的不是ogg嗎
況且你們要那麼高質做什麼

**Comment by ghost** [comment]
诶对啊，突然想起来了，Minecraft也是使用ogg。

**Comment by jacky8399** [comment]
> 你的世界（霧

MC以前還有用.mus的呢
