### ISSUE TITLE
@DLaboratory 请立即删除using namespace std;

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorld#23]
> -using std::string;
> -using std::vector;
> -using std::pair;
> -using std::unique_ptr;
> -using std::map;
> -using std::cout;
> -using std::endl;
> -using std::max;
> -using std::min;
> +using namespace std;

这是一种非常危险的行为：以后如果标识符重名了，将会造成大量的未定义行为
@abc612008 你来说明一下为什么不能这样干

**Comment by ghost** [comment]
@ascchrvalstr 取`std`中已经存在的名称给自己编写的程序中存在的标识符的命名，谁会干这种事情？你用`std::set`和`NEWorld::set`区分开，编译器是能区分开，但是你看看，程序的可读性怎么样？先不考虑前面加这么一个冗杂的`namespace`造成的代码繁杂，如果你光光看到一个`vector`，你的第一反应当然是C++ STL中的`vector`容器(如果你的开发经验很naíve，看到`vector`这几个字母不会立刻条件反射，那就算了吧。)，我们的代码里再出现一个`NEWorld::vector`不是捣乱吗？稍有C/C++开发经验的人都能看出，取`std`中已有的名字，就是螳臂当车的歹徒。

**Comment by harrynull** [comment]
这确实不是个好习惯，没人会故意去用，但总有人会误用。
用原来的写法一个新class只要using一次就行了，也不算麻烦啊

**Comment by ghost** [comment]
@abc612008 规避`std`已有命名是最基本的开发规范。

**Comment by bridgekat** [comment]
然而std中有些不常用的东西的名字没几个人知道，说不定就会跟这些名字搞混
// 撕逼大战即将开始

**Comment by bridgekat** [comment]
@ascchrvalstr 应该记得那个pipe 233

**Comment by ghost** [comment]
@qiaozhanrong 所以在开发的时候，如果遇到std中已有的名字，第一反应就应该是换名字。取已有的名字，故意不改，这种行为就应该拉出去毙了。

**Comment by ghost** [comment]
写几十行
using std::map;
和一行
using namespace std;
哪个更好啊？

NEWorld里面又没有八九十年代写的历史遗留代码，“为了避免命名冲突”这条理由
说不过去。
