### ISSUE TITLE
关于CppCheck检查出来的问题

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorld#26]
[NEWorld_checklog.xml](http://pan.baidu.com/s/1eRPBnKu)
请各位开发人员下载该文件并用CppCheck GUI打开，然后解决自己范围内的问题。

**Comment by ghost** [comment]
我们需要重写大部分代码，不仅是把Server和Client分开的需要，某些代码片段确实也让人浑身难受。

**Comment by ghost** [comment]
所以有些问题可以不管了，直接重写算了。

**Comment by DWVoid** [comment]
当时GUI主要是我和qiaozhanrong写的，不过现在不太想弄

**Comment by taxerap** [comment]
gui类的蛋疼简直可以比得上mc的sh*t了。。。什么xmin的，意义不明啊。。。
当初采纳 @abc612008 的建议用xywh不就好了。。。

**Comment by DWVoid** [comment]
@NPCTheSBest 其实当时我想用Rect，然后事件响应用虚函数和回调函数，但是某乔完全理解错了我的意思。。。

**Comment by bridgekat** [comment]
@NPCTheSBest xmin，xmax是控件左右端的x值；ymin，ymax是上下的y值
与xywh的换算：
xmin=x
xmax=x+w
ymin=y
ymax=y+h

**Comment by jacky8399** [comment]
你們NEWorld有一個好，就是代碼夠混亂，把所有新開發者都拒諸於門外

**Comment by harrynull** [comment]
重写了
