### ISSUE TITLE
格式极为混乱

### ISSUE THREAD

**Issue by idkidknow** [Infinideastudio/NEWorld#3]
#### 从Definitions.h中变量的命名可见一斑

其他文件亦是如此
有全小写的，有驼峰命名法，还有帕斯卡命名法
完全不统一
#### 函数的大括号的位置也是不统一

有在行末的，有另起一行的
#### 有些代码连点注释都没有

看得懂代码又不一定懂你的意图
#### -------------------------------------------------------------------

应说明如何贡献，得有个统一的标准，否则代码只会越来越乱
要写注释啊！说不定哪天自己都不知道自己写的代码是在干什么

**Comment by ghost** [comment]
围观。
目前，在`0.5.0`分支中，我用`astyle`对所有代码进行了Allman/BSD风格的格式化，最近我也在人工审查代码。

**Comment by DWVoid** [comment]
写的人不一样，个人习惯有差别，我就习惯不换行的

**Comment by ghost** [comment]
根据软件工程的基本法，一个软件项目应该要有一个统一的代码风格标准。

**Comment by HydroH** [comment]
[**@DREAMWORLDVOID**](https://github.com/DREAMWORLDVOID) commented on [2016年3月12日 GMT+8下午5:04](https://github.com/Infinideastudio/NEWorld/issues/3#issuecomment-195699062):

> 写的人不一样，个人习惯有差别，我就习惯不换行的

这是一个合作项目，不能按一个人的习惯来啊

**Comment by DWVoid** [comment]
@HydroH 也许规定应该更严格一点。目前我们的协作规定还不是那么明确，好像主要是以visual studio的文件标准来的。

**Comment by DWVoid** [comment]
我建议，为了避免不必要的编码问题，注释要用全英语，否则不同平台协作时会出现严重乱码。

**Comment by ghost** [comment]
@DREAMWORLDVOID 建议使用UTF-8编码来统一中文编码。

**Comment by DWVoid** [comment]
没用。windows上很多编辑器并不支持utf-8

在 2016-03-12 22:31:03，"D Laboratory" notifications@github.com 写道：

@DREAMWORLDVOID 建议使用UTF-8编码来统一中文编码。

**Comment by ghost** [comment]
这样的话，那就只能全英语注释啦~

**Comment by ghost** [comment]
������GFW������������������������������������������������������

**Comment by ghost** [comment]
卧槽，怎么涉及到敏感词，全都乱码了

**Comment by idkidknow** [comment]
@DREAMWORLDVOID windows？编程用的编辑器是不可能没有UTF-8的，要跨平台也是用utf-8方便

**Comment by harrynull** [comment]
UTF8一般可以
如果不支持说明IDE太老了， 换一个吧

**Comment by bridgekat** [comment]
@DREAMWORLDVOID 关键我们英语水平又不是怎么太好，过会大家可能互相改注释中的语法错误什么的，然后有些地方的英语只有写注释的人能看懂，还不如用中文然后UTF8编码

**Comment by DWVoid** [comment]
devcpp不认utf8-然后发一堆乱码，还不如用chinglish谢谢

在 2016-03-20 21:06:30，qiaozhanrong notifications@github.com 写道：

@DREAMWORLDVOID 关键我们英语水平又不是怎么太好，过会大家可能互相改注释中的语法错误什么的，然后有些地方的英语只有写注释的人能看懂，还不如用中文然后UTF8编码

**Comment by bridgekat** [comment]
@DREAMWORLDVOID 那就别用Devcpp呗

**Comment by DWVoid** [comment]
我的vs又坏了，过渡一下

在 2016-03-21 20:16:02，qiaozhanrong notifications@github.com 写道：

@DREAMWORLDVOID 那就别用Devcpp呗

**Comment by DWVoid** [comment]
还有最近不管改什么都别动和窗口和gui有关的部分，我在重构

在 2016-03-21 20:16:02，qiaozhanrong notifications@github.com 写道：

@DREAMWORLDVOID 那就别用Devcpp呗

**Comment by jacky8399** [comment]
寫代碼也是要按照基本法啊 你們啊 Naive

**Comment by ghost** [comment]
@jacky8399 拖出去续了!

**Comment by jacky8399** [comment]
你們啊，千萬要記住，不要“見得風，是得雨”，接到這些消息，你們本身也要判斷，知道嗎？@DLaboratory

**Comment by ascchrvalstr** [comment]
你们这样是不行的

**Comment by ascchrvalstr** [comment]
UTF-8终究要用的
格式是必须改的
然而并没有几个人来干这些吃力不讨好的事情
你改了，别人就和你撕逼，说你不能“见得风，识得雨”，然后又在那边revert。。。改了也白改。。。

**Comment by jacky8399** [comment]
現在的人說著說著就開始膜蛤了 你們這樣不行啊 將來寫代碼出了甚麼差錯 你們也有責任吧

**Comment by ascchrvalstr** [comment]
格式大部分已经改正
