### ISSUE TITLE
Git库什么情况?

### ISSUE THREAD

**Issue by ghost** [Infinideastudio/NEWorld#35]
谁把Git库覆写了，居然没有通知所有开发者去重新克隆，我还以为是一个简单的conflict，直接合并了。白洗了。

**Comment by dtcxzyw** [comment]
现在应该无法编译吧？

**Comment by bridgekat** [comment]
?

**Comment by ghost** [comment]
```
dlaboratorydeMacBook-Air:NEWorld dlab$ git count-objects -v
count: 0
size: 0
in-pack: 2082
packs: 1
size-pack: 786
prune-packable: 0
garbage: 0
size-garbage: 0
```

现在已经复写完成，恢复到233个commit的状态，请所有开发者删除原有NEWorld目录，重新克隆。
@Infinideastudio/neworld-team @Infinideastudio/cppgroup

**Comment by DWVoid** [comment]
@DLaboratory 现在Mac上能编译了吗？

**Comment by ascchrvalstr** [comment]
@DLaboratory 还有什么要擦除的内容吗？

**Comment by ghost** [comment]
@ascchrvalstr 应该不需要再擦除了。
