### ISSUE TITLE
NEWorld将走向何方

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorld#37]
@DLaboratory 感谢你让我们学会了开发的基本准则。
现在你不想开发了，可是我夜夜听见火车的车轮在远处轰鸣的时候，我一个人沉思的时候，甚至我和别人在聊天的时候，我也经常会突然停下来，心里默默地想着，你在这个项目里，到底充当了多么重要的一个角色。
你是NEWorld的全部希望，你走了，NEWorld也就完了。
坚持你最初的信念吧，

戴宇同
5.4 00:00:00

**Comment by ascchrvalstr** [comment]
开发人员的素质是可以改变的，代码风格是可以改变的——事实上并没有什么东西可以阻挡我们。
记得你半个月前的issue`跨平台化改造`吗？这足以说明你对我们的帮助是多么巨大。
没有你，我是不可能去深入学习Git的；没有你，我是不可能去学习boost的……
即使你已决意离开，我也为你所作的贡献而对你无比敬佩。

**Comment by taxerap** [comment]
嘛，让他和SSS慢慢叙旧去吧。他要走，我们也不能挽留。

**Comment by harrynull** [comment]
@DLaboratory 看到你的commit后，我不得不骂一句。
你走就走呗，你把你的贡献删掉干啥？从没见过你这么自私的。
你把所有贡献删除，NEWorld从此停止更新，这就是你想见到的吗？好了，NEWorld不开心了，你满意了是吧？

亲手给了我们希望，又亲手把希望给磨灭？你想干啥？来玩弄我们是吗？

是不是不允许别人有点不同的意见？是不是我说你的代码格式与现在的不一样，你就觉得被侮辱了，被鄙视了，我认为你的示范代码有点问题，提出我的见解，然后你就觉得我是在挑战你的权威？“既然你们觉得我这么不重要，我都是错的，那我就走呗”，然后走的时候再把你的东西给删掉，好让我们良心发现你的重要性？

你一直说不对事不对人，是吗？

> “而且带宽和流量'富裕'的很”
> 既然开发者有他们自己熟悉并喜爱的代码缩进风格，也有他们自己熟悉并喜爱的变量名和函数名风格

我没有权利让你留下，但你可以选择留下。
我没有权利让你再三思考，但你可以选择再三思考——想想你这段时间做了什么，现在做了什么。

我承认你功不可没。
但是，
为什么你既然给了我们希望,却为什么又要给我们绝望？我是看着NEWorld成长的人，而我又要看着它死去？

语气有点冲，若有冒犯，望原谅。

一个“不辨菽粟”的人
Null
2016.5.4

**Comment by DWVoid** [comment]
看来以后这个项目需要信仰

**Comment by bridgekat** [comment]
@ascchrvalstr @abc612008
他如果执意不回来，我们也只能自己做了。。。

**Comment by ghost** [comment]
我严重打乱了你们原本的开发步骤。我在把我所认为的一个软件工程应该有的样子强加在你们身上。我这三个月干了什么？
1. 让NEWorld能够方便地克隆
2. 让NEWorld能够在UNIX平台上编译
3. 倡议NEWorld改变它丑陋的代码结构
问题是，NEWorld的游戏系统在这三个月有任何质的变化吗？既然你们在过去的两年都能按照你们的结构开发下去，我来搅和一顿，不是捣乱吗？你觉得我带给NEWorld希望，我反而觉得我的出现干扰了NEWorld的前进道路。

**Comment by ghost** [comment]
而且，我实在是觉得，我给NEWorld写不下去代码了。
- 这是一个从FreeBASIC翻译过来的软件，这种面向过程的结构和C++的语法掺和在一起，活生生写成C with namespaces and classes，我消受不起。
- 开发人员普遍对Git、对C/C++、对计算机底层原理、对算法与数据结构了解甚浅，没有什么共同语言。
- 开发人员考虑问题的着眼点与思路，过往经历，写代码的习惯等和我相差太远，很难想到一处去。
- 我对代码风格的严重挑食，对Java的代码风格存在极端的、心理上和生理上的反感、排斥和呕吐。

我也不觉得什么“功不可没”，我只不过是一个学生而已。只是，我不能陷在一滩无边无际的沼泽里。

**Comment by ghost** [comment]
这一两个星期，受各种方面的影响，我的精神状态不是很稳定，昨天晚上以及前几天的行为，算是幼稚的发脾气吧，如果大家觉得反感，我在这里道歉。至于“离开”和“不离开”，这也是我在气头上说的话。
我现在说明：**我不会再参与NEWorld写代码的主力**，我以后的角色大概就是一个坐在旁边看着的observer和navigator吧，然后就是只写一写少量的代码。

**Comment by WenceyWang** [comment]
以我的视角说一个吧，我一开始来的时候git其实挺小（
一开始我也一副大力推动改变的意思，可是我自己能力不够而且没时间。
我之前的经验是.Net 上的。
我当时也在群里说了不少，包括团队管理，任务分配之类的，没什么成效，大家还是原来的样子，我也犯懒了于是就没再管，后来学习也紧张了。
@DLaboratory 你对项目所做的贡献是有目共睹的，你已经依靠自己的行动事实上的管理着这个项目。
我以前说过大概意思是NW有必要把现在的代码丢掉直接重新设计架构编写，否则这个项目希望不大。
由于个人原因，接下来一段时间我还是比较忙没法参与NW，但我希望我们能向着一个更好的方向发展。

**Comment by WenceyWang** [comment]
另外，像这样的开源项目，确实有必要有一个人作为PM总管整个开发过程，这样的工作很累而且在这里也没有什么报酬。
事实上不只是这一个项目，整个Infinidea都面对着这样的问题，现在的项目，要么是一个人开发别人看热闹，要么就是像NW这样“混乱邪恶”各自为政搞得这个药丸的样子。
不只是NW，我们需要一个有效的管理多人参与开发的项目的方式。

**Comment by WenceyWang** [comment]
另外@DLaboratory ,不管你如何选择，我都希望说一句，谢谢，你完成了我想做而没有做到的事情。

**Comment by ghost** [comment]
为什么我给NEWorld写不下去代码？那些表层的原因固然重要。同时，另一方面，我现在也很迷茫。NEWorld的代码结构这么糟糕的背后，还是反映出了一些问题的。开发人员的经验、意识、知识储备不是我喊破喉咙就能改变的。人没有丝毫的改变，把NEWorld重写几十遍，也都是重蹈覆辙，虚度光阴。
NEWorld和同种类的项目，Minetest、Terasology、TrueCraft、Craft相比，**差距体现在哪里？**这是开发者需要自己去思考的问题，而且是一个需要从不同方面思考上几个星期的问题。嚷嚷着“我们要重构！”、“这个功能该怎么实现？！”，猴急猴急地写代码解决不了任何问题，最终结果只会是再写出一个糟糕透顶的NEWorld出来。
NEWorld将走向何方，这个问题就取决于，开发者们怎么去改变“不辨菽粟”的状况？

顺便说一下，我在个人的账户下开了一个[NGWorld](https://github.com/DLaboratory/NGWorld)的repo。我不会再花大把的时间去给NEWorld写代码，而是悠闲地在NGWorld上做一些实验，所以，以后一段时间内，NEWorld中基本见不到我的commit了。

**Comment by ghost** [comment]
我在2月的时候恰巧偶遇了NEWorld，我不是NEWorld的创始人，更不是NEWorld的主要开发者。
我是一个路人，真正影响NEWorld的是你们自己。
**你们是什么样的，你们的作品，NEWorld，未来就是什么样的。**

**Comment by WenceyWang** [comment]
额，从这个角度说，NW注定是死掉的。
本来NW只是一些小孩子的沙子城堡，而包括我和 @DLaboratory  的一些人却希望使它成为真正的城堡，明显没有什么希望。
我想到我原来在学校社团收到的社员们交的所谓作业代码，几乎所有人的代码都一模一样而且过不了编译。
从这个角度，Infinidea也没有什么真正的创造力。

**Comment by DWVoid** [comment]
@DLaboratory 关于代码的问题这个没办法。当初Null做翻译工作（前生NEWorld-Cpp，github上还保留着）的时候我曾经提过建议（那时代码还很少），没人采纳（说是为了效率，其实估计自己都不清楚STL等等的工作原理）。后来想改都难，逻辑冗长，多次重写都以失告终，自然就没人想改了。

**Comment by harrynull** [comment]
@DLaboratory 这样就够了，假如有一天，NEWorld的代码水平提升了，你再回来也不迟。
另外，对昨天早上说的话再一次抱歉

**Comment by bridgekat** [comment]
@DLaboratory 写出来只是为了好玩和积累经验，你们能够帮助我们做得稍微好一些就够了。。。没必要做得很完美。。。

**Comment by ghost** [comment]
所以你们自己的态度就决定了你们作品的质量。

> 没必要做得很完美。。。

**Comment by ghost** [comment]
> 你们能够帮助我们做得稍微好一些就够了。。。没必要做得很完美。。。

既然官方开发者对这个项目的态度就是上面写的这样，代码写成什么样是什么样，只要能运行起来就不错，代码结构做成那副样子也不闻不顾，最后发现在那种糟劣的歪歪扭扭的积木堆上再加上新代码举步维艰，于是便直接弃坑。
你们主观上没有故意地去做我上面列举的事情，但是做出来的效果，和上面有什么区别吗？
或许年龄是一个因素，但绝对不会造成那么大的影响，更不是一种借口，一张万能的挡箭牌。难道小学生、初中生，就有理由学不会那些知识吗？数学比我不知道高到哪里去了的中学生，一抓一大把。年龄小，知识储备就应该理所当然地小，我不能认同。
我很幼稚啊，我居然还把NEWorld这个项目当成一个软件工程来看。你们的态度如此，我觉得我退出NEWorld的开发，清理掉我写的代码，另起炉灶自己单干，并不过分。

**Comment by harrynull** [comment]
@DLaboratory 那只是最初的想法而已，后来大家的态度都转变了，认真了

**Comment by Miigon** [comment]
精彩的故事
