### ISSUE TITLE
建议加入boost库

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorld#38]
使用boost库而不是C++14自带库的原因是：很多编译器不滋瓷C++14标准，而且有些滋瓷也的是实验性的，不知道有无bug。
而且更重要的是，很多boost库不在标准里（比如`boost::operators`），再看看我们的Vec3的实现代码：

``` C++
    bool operator< (const Vec3& rhs) const
    {
        if (x < rhs.x) return true; if (x > rhs.x) return false;
        if (z < rhs.z) return true; if (z > rhs.z) return false;
        if (y < rhs.y) return true; return false;
    }

    bool operator> (const Vec3& rhs) const
    {
        if (x > rhs.x) return true; if (x < rhs.x) return false;
        if (z > rhs.z) return true; if (z < rhs.z) return false;
        if (y > rhs.y) return true; return false;
    }

    bool operator== (const Vec3& rhs) const { return x == rhs.x && y == rhs.y && z == rhs.z; }
    bool operator!= (const Vec3& rhs) const { return x != rhs.x || y != rhs.y || z != rhs.z; }
    Vec3 operator+ (const Vec3& rhs) const { return Vec3(x + rhs.x, y + rhs.y, z + rhs.z); }
    Vec3 operator- (const Vec3& rhs) const { return Vec3(x - rhs.x, y - rhs.y, z - rhs.z); }
```

如果使用`boost::operators`，代码将简化很多。以后写到更复杂的类型的时候，重复代码会越来越多。
`boost::gil`可以简化Texture模块也是一个例子。
`boost::log`可以代替logger也是一个例子。
`boost::filesystem`可以简化存档相关的方方面面。
`boost::format`可以提供增强的安全性。
`boost::date_time`可以很好地代替某`tm`结构。
`boost::locale`可以进行本地化。
`boost::pool`可以提高内存分配的效率。
······

**Comment by DWVoid** [comment]
Boost库一大缺点在于其是重型库，生成需要相当长的时间，配置比较复杂，加入这种库需慎重 @ascchrvalstr

**Comment by ascchrvalstr** [comment]
@DREAMWORLDVOID 你不会部分编译boost吗？你不会用bjam吗？而且boost只有少数几个需要编译的。

**Comment by DWVoid** [comment]
@ascchrvalstr 我不反对，反正早上已经配置好了

**Comment by harrynull** [comment]
反对，理由如下
1. 加入boost库对于没有用过boost的开发者不友好
2. C++14标准已经广泛普及，身为开发者，有义务升级到最新的编译器，考虑编译器标准支持程度没有必要
3. boost比较巨大，累赘没有必要

**Comment by ascchrvalstr** [comment]
@abc612008 反驳，理由如下
1. 连boost库都没接触过，那说明开发者水平低下。（而且boost大多数库都非常容易懂且有完善的文档，而C++标准中的库文档较少）
2. 以`TDM-GCC`为例，它对C++14的支持有bug，很多头文件在`experimental/`目录下就说明支持是未经过完全测试的，而boost库在被应用的过程中已经证明了它的优秀性。
3. 如果一个人连部分编译boost都不会，那他的水平也不可能很高。

**Comment by harrynull** [comment]
变着花样骂我水平低下……

**Comment by harrynull** [comment]
boost最新版本压缩包都高达一百多MB……

**Comment by DWVoid** [comment]
这到是。v160展开要将近1G

**Comment by ascchrvalstr** [comment]
V1.61出了。。。新增了dll库，用来加载动态库的。。。pluginSDK不用这个库的话就要写三倍的代码。。。

**Comment by DWVoid** [comment]
@ascchrvalstr 我个人同意加，毕竟里面很多模板还是很有用的。现在得看 @qiaozhanrong 的想法
还有，那个PluginSDK我觉得应该直接输出类，否则到时候还要做二次封装

**Comment by bridgekat** [comment]
@DREAMWORLDVOID 我中立

**Comment by DWVoid** [comment]
所以现在到底加不加（反正我不急，最近在搞ray trace）

**Comment by harrynull** [comment]
加吧

**Comment by ascchrvalstr** [comment]
那就加了？

**Comment by harrynull** [comment]
@ascchrvalstr 加吧加吧，懒得吵了
但是我还是建议只有在用到标准库以外的东西才用boost库的（优先标准库，标准库不稳定再用boost）

**Comment by bridgekat** [comment]
最终结果：同意加入
