### ISSUE TITLE
是否可以引入Objective-C++

### ISSUE THREAD

**Issue by DWVoid** [Infinideastudio/NEWorld#39]
在编写UI时发现GC是个大头，而利用c++的各类ptr则略显麻烦。oc提供了autoreleasepool这种解决方案，正好个人会oc而gcc也支持oc。

**Comment by rand-fly** [comment]
可以自己实现一个autoreleasepool（我又在灌输cocos 思想了）

**Comment by ascchrvalstr** [comment]
智能指针你不习惯？好好看看`regulations.md`吧
绝对不会引入objective-C++的。
@qiaozhanrong @abc612008 @DLaboratory 你们出来个人把这个issue关了，我可不想被背黑锅

**Comment by harrynull** [comment]
只为了这个理由引入objc太不划算，成本很高，不是所有人都会objc的

**Comment by ghost** [comment]
Mac OS X用户表示很尴尬，Apple家是最适合Objective-C语言的平台，C/C++只能算是二等公民，然而我却根本不会Objective-C语言，反而还对其语法表示非常不爽。
