### ISSUE TITLE
以后与我沟通请通过Github发邮件给我，谢谢配合

### ISSUE THREAD

**Issue by DWVoid** [Infinideastudio/NEWorld#4]
@DLaboratory @WenceyWang @abc612008 @qiaozhanrong @riteme @dtcxzyw @HydroH

**Comment by ghost** [comment]
新开一个Issue什么鬼

**Comment by DWVoid** [comment]
只是我被迫退群了

在 2016-03-13 17:12:37，"D Laboratory" notifications@github.com 写道：

新开一个Issue什么鬼
