### ISSUE TITLE
来个人，把语法错误修一下

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorld#40]
每个文件开头的an free game谁帮忙改一下

**Comment by DWVoid** [comment]
.......

**Comment by bridgekat** [comment]
DLab说了他一开始打的是an open-source game，现在把open-source改成了free，然后an忘了改了。。。以后让他重新弄一下，反正他一开始是写脚本加的

**Comment by bridgekat** [comment]
已经修好
