### ISSUE TITLE
以后投票是否进行版本库重构及通知重新克隆repo的往这里发

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorld#41]
今天将要洗掉`include/GLFW/glfw3.h`及`include/ft2build.h`还有`build/VisualStudio_v14/UIEngine`

**Comment by bridgekat** [comment]
就不能一个月洗一次吗，几个代码文件就让大家重新clone(╯‵□′)╯︵┻━┻

**Comment by ascchrvalstr** [comment]
[建议]把每月20日定为洗文件日。
现在发现了几个垃圾文件。DataKit by @DREAMWORLDVOID (`DataKit`目录)，NNN(src/`NNN.h`,`NNN.cpp`,`ByteOrder.h`)。理由是这些文件都没有使用过任何一次。
另外，建议把@DLaboratory 等人写的example code擦除。

**Comment by ascchrvalstr** [comment]
@Infinideastudio/cppgroup 请立即重新克隆repo

**Comment by ascchrvalstr** [comment]
此次洗掉了NNN和example code

**Comment by bridgekat** [comment]
@ascchrvalstr 说好20日的呢

**Comment by ascchrvalstr** [comment]
@qiaozhanrong 20日要忙考试(╯‵□′)╯︵┻━┻

**Comment by bridgekat** [comment]
@ascchrvalstr QAQ

**Comment by Miigon** [comment]
就算重构也没有必要重新克隆，只需pull & checkout
