### ISSUE TITLE
移除DLaboratory编写的所有代码

### ISSUE THREAD

**Issue by ghost** [Infinideastudio/NEWorld#43]
*

*

**Comment by DLaboratory** [comment]
废话不多讲，我请求大家做下列事情：
1. 移除我编写的所有代码。
2. 在记忆中忘掉我。
3. 合理乐观地认识自己，严肃地、不开玩笑地讲，我非常看不惯整天说自己“我最垃圾”、“还有谁比我更垃圾”的行为。
4. 合理地开玩笑。不是所有的场合都适合开玩笑的。在不适当的上下文、语境、事件时开玩笑会激怒他人。你在那里嬉皮笑脸，请问你是在作死，还是在故意惹怒别人？

**Comment by DLaboratory** [comment]
逼我离开Infinideastudio的原因是好几条叠加综合的。
求各位放过我，以后不要再认识我了，也别再找我了。我受不了了。

**Comment by DLaboratory** [comment]
Follow我的那几个人，我请求您解除对我的Follow。就当我们从来没有见过。

**Comment by DWVoid** [comment]
这里发生什么了？

**Comment by ascchrvalstr** [comment]
我们自己弄吧= =

**Comment by DLaboratory** [comment]
把这些事情实现了吧，谢谢！

**Comment by DLaboratory** [comment]
在实现这些请求之前，请不要关闭这个issue！

**Comment by DLaboratory** [comment]
看样子根本没有人去着手干这些事情。我都怀疑有没有人真的认真读过我写的请求。然后就毫无理由地关闭了issue。
