### ISSUE TITLE
建议使用boost::thread代替std::thread

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorld#44]
`std::thread`的效率差是众所周知的。
不要以为<thread>是从`boost::thread`来的。
`boost::thread`提供高效的线程操作。

**Comment by ascchrvalstr** [comment]
刚才没打完，然后不小心按了回车

**Comment by harrynull** [comment]
现在使用std::thread只是为了方便起见，以后会调整的

**Comment by bridgekat** [comment]
WinAPI + pthreads大法好

**Comment by ascchrvalstr** [comment]
boost::thread大法好

**Comment by Miigon** [comment]
单一进程大法好【误
