### ISSUE TITLE
世界總管什麼鬼

### ISSUE THREAD

**Issue by MichaelRix** [Infinideastudio/NEWorld#45]
```
BlockManager.h
WorldManager.h
```

就不能叫`Controller`麼。

**Comment by WenceyWang** [comment]
我倒是见过一个叫做Task Manager，一般翻译叫做"任务管理器"。
Controller 让人想到MVC

**Comment by jacky8399** [comment]
我比較滋瓷`BlockRegistry`
然而為甚麼`BlockManager`管理的是`BlockType`啊
況且Type是種類吧

**Comment by MichaelRix** [comment]
@WenceyWang 蛤，其實我就是這個意思。

另外`Controller`比`Manager`好聽，不過既然是容器，那這兩種都不能叫。

亦可賽艇啊。

**Comment by DWVoid** [comment]
我也支持Block Register，这样管理比较方便

**Comment by Miigon** [comment]
blockmanager没有什么问题，“管理方块”的类，把方块集中，提供对其整体的访问和查找。
worldmanager如果manage的是多世界的话就合理 但如果是单世界管理世界内部状态的话应该直接命名为world能够比较清晰
xxxmanager应是管理多个xxx的

以上，从命名清晰性出发的个人意见

**Comment by bridgekat** [comment]
@Miigon 确实是像你的想法命名的。。。

**Comment by Miigon** [comment]
> @Miigon 确实是像你的想法命名的。。。

DLaboratory 还是带给了你们好东西的

**Comment by bridgekat** [comment]
@Miigon QAQ
可是他现在走了。。。你最好别at他，他让我们不要再跟他联系。。。

**Comment by Miigon** [comment]
修改了，来得及吧...
实际上，初中生、高中生能做到这种程度已经是很了不起了
我仿佛在你们的代码中看到了我自己的影子，成长。
接下来的日子我会帮忙做一些跨平台移植之类的工作的。

**Comment by bridgekat** [comment]
QAQ谢谢。。。

**Comment by harrynull** [comment]
@Miigon 有兴趣加入开发组吗？(QQ群/write权限)

**Comment by Miigon** [comment]
好吧，但是学生党可能只能提供有限的支援了

**Comment by harrynull** [comment]
@Miigon 你的QQ?
