### ISSUE TITLE
你们这些人啊，用库图样图森破，有时乃义务

### ISSUE THREAD

**Issue by Miigon** [Infinideastudio/NEWorld#47]
不要动不动就boost的，几百m多不好，瞧瞧西方那一套，libuv，轻量才是坠吼滴。raknet做实时游戏，效率不知高到哪里去。

最近又出现了std::thread效率差的理由引入boost::thread库...直接说std的不如boost是不是有种钦定的感觉？效率不是取决于具体实现的么？这个锅应该编译器背啊。

**Comment by abc612008** [comment]
没有任何钦点的意思啊，还是要按照项目的开发协定，相关规范来产生。但是库的更替也要按照相关规定啊，当然我们的决定权也是很重要的，到时候我们会表态的。

**Comment by Miigon** [comment]
嗯，就表示boost引入要谨慎，linux编译个boost(即使部分编译)都比编译这个游戏久(的多)

**Comment by DWVoid** [comment]
同感。上次ubuntu上跑b2用了一个半小时。不过安装了不用总觉得有点亏

发件人: noreply@github.com [mailto:noreply@github.com] 代表 Miigon
发送时间: 2016年6月22日 10:59
收件人: Infinideastudio/NEWorld NEWorld@noreply.github.com
主题: Re: [Infinideastudio/NEWorld] 你们这些人啊，用库图样图森破，有时乃义务 (#47)

嗯，就表示boost引入要谨慎，linux编译个boost(即使部分编译)都比编译这个游戏久(的多)

**Comment by ascchrvalstr** [comment]
用boost是经过考虑的

**Comment by Miigon** [comment]
@ascchrvalstr 那还烦请你解释一下为何不考虑使用轻量级的代替方案而是使用boost吧。

**Comment by harrynull** [comment]
其实上次就是否用boost撕逼了一个星期
大概用boost是为了里面的asio，其他的只是顺手用一下

**Comment by bridgekat** [comment]
主要是@ascchrvalstr 觉得boost比较吼，而且极其反对我们造轮子，我们就答应了（懒得撕逼233），然后编译和IntellliSense就慢了几个数量级。。。
还好我后来做了个Logger的轮子，不然更慢，VS要卡三分半钟才能给类名上色。。。

**Comment by Miigon** [comment]
socket库当然还是不造轮子的好，但boost最好作为最后方案

推荐看一下这个：https://sourceforge.net/projects/asio/files/asio/1.10.6%20%28Stable%29/
asio的non-boost版本，不依赖boost，源码只有1.5M，大多数情况header only

**Comment by MichaelRix** [comment]
你們都是同樣C++，同樣摸蛤，吃棗藥丸。

NIl你們不要又氣走一個。
