### ISSUE TITLE
C# API中的命名方法

### ISSUE THREAD

**Issue by WenceyWang** [Infinideastudio/NEWorld#50]
C# 常用的命名方法大概是对于类的公有方法，属性之类用大驼峰，私有方法属性之类用小驼峰。
出于方便C# 的开发者的目的，在C# API 中应当偏向于使用C# 的命名方法。

**Comment by ascchrvalstr** [comment]
等C++的PluginAPI穩定后就改

**Comment by jacky8399** [comment]
出于方便.NET的开发者的目的，在.NET API 中应当偏向于使用.NET的命名方法。
可以 這很.ctor()

**Comment by Miigon** [comment]
.NET不是可以再一层封装么
