### ISSUE TITLE
为何有库可以链接不链接要用预编译？

### ISSUE THREAD

**Issue by Miigon** [Infinideastudio/NEWorld#52]
要知道在Linux上每次compile都要编译几个boost库很难受的。
本来这种问题就能通过链接静态库来解决。

**Comment by ascchrvalstr** [comment]
鏈接靜態庫過不了CI

**Comment by bridgekat** [comment]
@ascchrvalstr 应该是有办法过的

**Comment by ascchrvalstr** [comment]
編譯器不一樣，g++對basic_string的實現是放在std::__cxx11命名空間中的，而g++-5不是這樣的。這導致了庫和對象根本不兼容

**Comment by harrynull** [comment]
@ascchrvalstr 奇怪啊，CI不就是一台小型临时的VPS吗，和真机一样的。难道在一台真机上都不能用链接静态库的方法吗。

**Comment by bridgekat** [comment]
@abc612008 他的G++编译器和CI上的编译器不兼容，导致他没有办法在本地编译出兼容CI上的环境的库

**Comment by harrynull** [comment]
@qiaozhanrong 那不能分开编译Boost和NEWorld

**Comment by bridgekat** [comment]
@abc612008 你问DYT吧

**Comment by Miigon** [comment]
配置gcc6啊，我的linux上编译就是用gcc6，或者也可以配置clang。
