### ISSUE TITLE
客户端与服务端是否真的需要动态链接

### ISSUE THREAD

**Issue by Miigon** [Infinideastudio/NEWorld#57]
客户端和服务端在这里被编译成为动态共享库，然后通过launcher启动
但是，问题是，客户端和服务端真的需要动态共享么？而不是通过PluginAPI单独的共享库？
launcher动态启动将为调试带来极大的麻烦，而且没有实际意义。

**Comment by bridgekat** [comment]
因为PluginAPI要调用主程序里的函数，所以主程序对于插件来说本身就是库，不知道编译成可执行文件后在*nix上能不能export函数给别的程序调用

**Comment by bridgekat** [comment]
如果可以的话当然是可执行文件坠吼了啊。。。

**Comment by Miigon** [comment]
> 不知道编译成可执行文件后在*nix上能不能export函数给别的程序调用

不能
准确上来说是在arm上可能出错
这些奇怪的做法都会变相破坏可移植性

> PluginAPI要调用主程序里的函数，所以主程序对于插件来说本身就是库

反对。主程序不可以是库，应该让`PluginAPI`export一个init函数，然后将主程序需要调用到的函数的指针发送给PluginAPI

**Comment by bridgekat** [comment]
@Miigon 一开始就是这么写的，后来实现起来太麻烦，然后SSS就建议这么弄，@abc612008 也同意

**Comment by DWVoid** [comment]
@Miigon 如果完全是导出C-风格的函数是可以这样做，而且也很方便，就看qiao的想法

**Comment by Miigon** [comment]
@qiaozhanrong 所以现在的插件设计是直接动态调用主程序内的符号？

**Comment by bridgekat** [comment]
@Miigon 对，或者说是“运行时静态链接”

**Comment by Miigon** [comment]
@qiaozhanrong `运行时`和`静态`矛盾了。。。
我再去各个平台测试吧，如果没问题的话就这样吧

**Comment by Miigon** [comment]
主要问题是gcc4.3以上的符号`visibility`默认不是`hidden`，所以就算不写`attributes`，内部extern的函数依然可见，包括main（虽然gcc5以下编译不了UILib就是了）

**Comment by ascchrvalstr** [comment]
> 就看qiao的看法

[权力制衡](https://program-think.blogspot.com/2016/06/USA-Separation-of-Powers-with-Balances.html)

**Comment by bridgekat** [comment]
`运行时和静态矛盾了。。。`
我说的意思是运行开始时通过dllexport dllimport什么的一次获取完所有API，而不是运行过程中动态获取函数地址。。我干脆把这种方式叫做运行时静态链接了2333

**Comment by Miigon** [comment]
我持保留

**Comment by Miigon** [comment]
所以结论就是使用executable了，PluginAPI嵌入shared，也就是取消launcher，没有异议的话就close了

**Comment by bridgekat** [comment]
@Miigon 你不是说ARM上不行吗

**Comment by Miigon** [comment]
@qiaozhanrong 我没说不行啊
只是调用方式可能要修改，也可能不用，谁知道呢

**Comment by bridgekat** [comment]
@Miigon 调用方式修改成啥

**Comment by Miigon** [comment]
@qiaozhanrong 我也不懂，没有涉足这方面的开发，只知道一二
总之这个无关，既然共享库能在安卓上正常工作，那NW在安卓上运行就可以编译成library（实际上安卓NDK也只能这么做？），在其他平台上编译为executable就没问题了，nwapi.h中加入个常量按平台判断就好
我关心的是在linux下gcc linker调用executable中的symbol的方法(without `boost::dll` or `dl`)

**Comment by Miigon** [comment]
结论：维持现状
