### ISSUE TITLE
请求修改构建输出文件名为简单文件名

### ISSUE THREAD

**Issue by Miigon** [Infinideastudio/NEWorld#58]
目前的构建结果文件名为`NEWorld`与`NEWorldServer`，大小写区分和长文件名对输入造成了不便

**Comment by bridgekat** [comment]
你想改成什么

**Comment by Miigon** [comment]
上次的`nwserver`和`nwclient`被你们revert了，理由是万恶的VS工程文件没有改名字。。。

**Comment by bridgekat** [comment]
蛤。。

**Comment by Miigon** [comment]
@qiaozhanrong 在[这个commit](https://github.com/Infinideastudio/NEWorld/commit/09db6554a4faa20ac2292ae8b740183515102af8)

**Comment by bridgekat** [comment]
额

**Comment by Miigon** [comment]
@qiaozhanrong 所以改不改？

**Comment by bridgekat** [comment]
@abc612008 你说呢

**Comment by harrynull** [comment]
这种东西是游戏内部使用的。所以
- 一方面麻烦也是对于开发者的，而且是一次性的劳动。
- 另一方面名字短的话对用户也不会有太大影响，因为用户不可见的，也就是说命名成c.dll/s.dll也没啥问题

综上所述，中立

**Comment by ascchrvalstr** [comment]
**(旁观人员，纯胡扯)**
建议使用nwclient/nwserver

**Comment by Miigon** [comment]
@abc612008 这个问题针对的就是开发者，而且绝不是一次性劳动，你说的一次性劳动仅限于你们那美好的gui世界

**Comment by harrynull** [comment]
@Miigon 不知道是不是理解有偏差，正常启动游戏是绝对不需要手动输入dll名字的

**Comment by bridgekat** [comment]
他的意思是如果修改CMakeLists.txt的话会比较麻烦

**Comment by Miigon** [comment]
@qiaozhanrong 并不是
@abc612008 试试用linux编译吧。

> 正常启动游戏是绝对不需要手动输入dll名字的

Naive.

```
make NEWorldServer
./launcher -f ./bin/libNEWorldServer.so server
```

```
make nwserver
./launcher -f ./bin/libnwserver.so server
```

你来试试第一种写法每次编译输入一次啊？

什么时候才能放下IDE

**Comment by bridgekat** [comment]
可以搞个.sh吧

**Comment by Miigon** [comment]
要是一开始就要搞sh我还搞cmake干什么。。。
cmake是跨平台的makefile生成器，makefile是用于编译的sh代替品

**Comment by harrynull** [comment]
@Miigon 以前一直是`./launcher client`的，不是你改成这种需要手动输入路径的模式的吗？然后你又来抱怨麻烦

**Comment by Miigon** [comment]
我改的是**可选**指定路径
你们用IDE来把文件编译到某个奇怪的目录里再用魔法指定工作目录
我用cmake把文件编译到bin里你告诉我`./launcher`怎么指定工作目录？
不争了，你都证明了修改与不修改对你们GUI世界没影响为什么还要和我争辩？

**Comment by harrynull** [comment]
@Miigon 一直都是要求生成到bin目录的吧……我不清楚最近发生了啥

**Comment by Miigon** [comment]
@abc612008 shell无法指定工作目录，就这么简单
或者说：

```
// 工作目录：.
$ ./bin/launcher -f ./bin/libNEWorldServer.so server // 此时工作目录在根目录，所以无法找到在bin内的库，需要-f
$ cd ./bin
./bin $ ./launcher server  // 此时工作目录在bin内，所以能够不加 -f 直接找到库，但是又因此无法找到在根目录下的资源文件
```

**Comment by harrynull** [comment]
@Miigon 所以不如全部统一到bin目录？

**Comment by bridgekat** [comment]
我早就认为应该统一到/bin里了。。。当初DYT大力反对QAQ

**Comment by Miigon** [comment]
@qiaozhanrong DYT的Github ID是？
如果要发布可以直接编译到bin里，整个bin丢出去，岂不美哉

**Comment by bridgekat** [comment]
开发过程中也编译到bin里吧。。。发布肯定得放进去的

**Comment by DWVoid** [comment]
而且最好按在配置分别生成，这样可以减少重编译时间

**Comment by DWVoid** [comment]
比如在Mac OS X上图形应用必须要闭包，目录搞不好的话到时候搞相对目录能过烦死人。。。

**Comment by ascchrvalstr** [comment]
我是滋瓷在AppVeyor上编译完自动发布，现在那东西没人维护了
我把_Learning Python, Programming Python和Python Docs_看完，Python入门了就回新创无际（大雾）

**Comment by Miigon** [comment]
资源文件放到bin中怎么样？

**Comment by bridgekat** [comment]
资源分开吧，因为他是可以改的

**Comment by bridgekat** [comment]
一般bin里都是编译之后的程序啥的
