### ISSUE TITLE
Another wheel：轻量级GameUI

### ISSUE THREAD

**Issue by bridgekat** [Infinideastudio/NEWorld#59]
我一开始对UI的设想就是给个SDL2的封装（Window类），再给几个控件类。。。
然后现在@DREAMWORLDVOID 的`GameUI`做成了UI控制整个程序的框架。。。
这样一来感觉有点复杂了，我觉得VOID这么做的目的主要还是为了控制布局（如果还有别的目的请评论）

我的想法是，布局用`百分比+偏移量`作为坐标应该也行了，理论上能实现`Grid`的所有效果。。。
因为`Grid`嵌套布局的坐标中也只有`绝对坐标`和`比例坐标`两种。。。
变量也只有窗口高宽。。。
确定一个点坐标的多项式最终可被化简为`(a0*窗口宽度+c0, a1*窗口高度+c1)`
我的`百分比+偏移量`坐标其实就是给定一个坐标的`a0`，`c0`，`a1`，`c1`来实现自动布局
说起来可能有点麻烦，但是NW的UI布局不会太复杂，用这种方式布局反而有简便的优势。。。

**Comment by Miigon** [comment]
所以你要钦定比例坐标和相对坐标咯？
偏移量是什么鬼

**Comment by bridgekat** [comment]
刚刚考虑了一下，@Miigon 的思路也很好，我们可以加一个Panel控件，然后可以设置实际大小和容纳大小，如果相等则可用于辅助布局（就像现在的Grid），如果容纳大小更大则可以做滚动条进行滚动，相当于现在的ScrollView。。。
Panel本身的位置和内部控件的定位依然根据`百分比+偏移量`进行定位。。。

**Comment by Miigon** [comment]
详细说明一下，为窗口元素添加包含关系(嵌套)，子元素的坐标是相对于父元素的，而最外层的元素则相对于屏幕原点，然后添加类似`panel`的元素用来整合组件
以Minecraft的物品栏为例：
首先定义一个`物品栏界面panel`，在按下i键之后显示这个panel，其中包含了`物品栏窗口panel`和`buff panel`，这两个panel是固定大小但位置是按比例居中的，`物品栏窗口panel`又包含各个物品格子的元素，这些元素的坐标是相对于`物品栏窗口panel`的
所以最后的结构是这样：

``` html
<Window name = "主窗口">
  <Panel name = "物品栏界面" visibility = "hidden" width = "500" height = "100" x = "50% - width/2" y = "50% - height/2">
    <Panel name = "物品栏窗口" width = "500" height = "300">
      <Panel name = "物品格子面板" width = "100%" height = "50 * 4" x = "100% - height"><!-- 假设一个格子的高度是50，总共4行 !-->
        <ItemSlot id=1 />
        <ItemSlot id=2 /><!-- .....!-->
      </Panel>
      <!-- 装备栏.....etc !-->
    </Panel>
    <Panel name = "buff窗口" visibility = "hidden" width = "0" height = "100%"/><!--此处的height代表其父元素"物品栏界面"的100%!-->
  </Panel>
</Window>
```

**Comment by bridgekat** [comment]
那就还是用Grid（Panel）的定位方法？

**Comment by Miigon** [comment]
当然我也希望有个界面布局管理器什么的那是最好的，还有布局描述语言，这样插件要扩展界面才能简单实现

**Comment by Miigon** [comment]
我不知道目前的是怎么实现的，因为我没有读或者修改过UILib的代码

**Comment by Miigon** [comment]
如果Grid是按照我现在的描述来写的话，应当是问题不大的
总的来说，这都是如何定位UI元素层面的问题，和`UI控制整个程序`没有什么关联
要明确，这个程序接受这几个输入：
- 窗口IO输入（键鼠）
- 网络IO输入

原则上讲，客户端的执行流程应该按照网络IO，也就是服务器来执行
但是，窗口IO输入的决定也是很重要的，到输入的时候程序会表态的。
这么理解可能简单些：

```
服务器 -> 网络IO -> 游戏核心 -> UI展示
UI输入 -> 游戏核心 -> 网络IO -> 服务器
```

游戏核心包含了世界、方块处理、移动处理之类的，而游戏核心通过调用UI展示模块，由UI展示模块来读取游戏数据并渲染出来，两者必须分离开，当你编码的时候，时刻想着如果将UI展示换为DX的可能性，如果能做到只修改UI展示模块就实现的话，大致上就差不多了

**Comment by DWVoid** [comment]
本来Margin就是从百分比+偏移量扩展的  @qiaozhanrong ，默认grid就是1*1，没有指定位置的控件都在第一格，你可以就当它panel用

**Comment by DWVoid** [comment]
如果要关联网络的话建议另外开一路线程处理，本来显示，事件处理就不在一个线程上

**Comment by bridgekat** [comment]
@DREAMWORLDVOID 额，我的建议是程序框架（主循环等）不要让GameUI做

**Comment by rand-fly** [comment]
这就是我希望的做法，以界面框架为核心（另外GameUI将来肯定会变成一个游戏引擎的

**Comment by bridgekat** [comment]
@renfei147 界面框架做结构不太好吧。。如果GameUI不是UI库而是引擎那还差不多

**Comment by jacky8399** [comment]
mc用的原來是xml啊 漲知識

**Comment by ascchrvalstr** [comment]
#define NEWorld WheelFactory

**Comment by Miigon** [comment]
但是，GameUI本身就需要一个窗口，窗口本身就需要一个循环
我的想法和 @DREAMWORLDVOID 一样，用多线程，主线程为UI线程
如果UI线程退出了，也能顺手关掉其他线程

**Comment by bridgekat** [comment]
我的想法是主线程里手动调用ui的init，pollevents和swapbuffers，就像glfw sdl一样

**Comment by DWVoid** [comment]
我的想法是让某UI成为各种Framework的集合，也就是说除了游戏逻辑以及渲染的顶层意外其他通用部分都由Framework管理

**Comment by Miigon** [comment]
@qiaozhanrong 

> 我的想法是主线程里手动调用ui的init，pollevents和swapbuffers

`主线程里手动调用`不就决定了event loop依然是在主线程中么
只是导出了个初始化接口而已
不过导出初始化接口毕竟还是能提高灵活性
@DREAMWORLDVOID 我觉得编写成framework很容易导致一些提供的东西从“可以用”变成“必须用”，限制了将来的发展，特别是需要用这个所谓framework来编写其他游戏时
“除非别无他法，否则不要编写复杂的程序” --Unix之禅

**Comment by bridgekat** [comment]
> 我觉得编写成framework很容易导致一些提供的东西从“可以用”变成“必须用”，限制了将来的发展，特别是需要用这个所谓framework来编写其他游戏时

+1
s

**Comment by ghost** [comment]
> “除非别无他法，否则不要编写复杂的程序” --Unix之禅

这句话不一定是真理，具体情况具体分析。

**Comment by Miigon** [comment]
当然，只是哲理
但是简单的东西总有好处的，对吧？
所以，早点得出结论吧

**Comment by ghost** [comment]
并不代表把程序设计成UNIX那一副简单模块的拼拼凑凑的样子就是好的。

**Comment by DWVoid** [comment]
本来的目的就是提高代码复用率。毕竟把一段功能相同的代码重复好几遍是完全没有必要的

**Comment by Miigon** [comment]
无所谓了，我讨论的简单仅限于不编写无意义的代码，还有让代码执行得“和看起来一致”，到此为止
结论才是重点，是作为framework来提供还是作为功能库来提供？
还有具体的界面布局方式

**Comment by DWVoid** [comment]
布局方式不需要任何的改变，只需要提供更多的简化接口即可

**Comment by Miigon** [comment]
@DREAMWORLDVOID 好的
我个人认为作为framework来提供也没有很大的问题，只要接口设计的好，还可以减少游戏本身需要做的事情（虽然不一定多余），所以这一点我支持保持现状

最后一个问题是 渲染是独立线程还是在主线程？
我是支持主线程，理由已经说了
你们的想法？@DREAMWORLDVOID @qiaozhanrong

**Comment by DWVoid** [comment]
目前对于NW来说纠结于UI并不是一个好主意。我认为还是先把NW的核心搞好（这部分我不会过多插手）目前我在考虑整体修正UI的框架（准确来说应该是MultiMedia Library），将目前的图形对象进一步拆解并且尝试简化接口。到时候可能需要比较多的人帮忙

**Comment by Miigon** [comment]
这并不是纠结，没有目标随缘写代码很容易导致悲剧
而且我认为这部分非常重要，但又非常简单，`渲染是独立线程还是在主线程？` 只有这个问题
讨论都要得出结论，否则就是白费了是吧？

**Comment by Miigon** [comment]
btw,我支持后者

**Comment by DWVoid** [comment]
@Miigon 对于为何不把渲染放在主线程上的理由我也已经充分说明了。大规模渲染处理的时候非常消耗CPU时间，尤其是目前的渲染框架采用了OpenGL。放在主线程有非常大的可能性导致阻塞事件处理

**Comment by Miigon** [comment]
但渲染都掉帧了，输入能处理也没意义吧
网络的话会开一个新线程的，所以不会受到渲染阻塞

**Comment by DWVoid** [comment]
而在目前游戏过程中游戏本身会捕获输入这点来说是非常危险的，因为可能导致电脑完全无法操作

**Comment by Miigon** [comment]
所以需要封装输入为事件？

**Comment by Miigon** [comment]
然后用注册Listenner的方式

**Comment by DWVoid** [comment]
现在采用的就是Listener，但是作为底层库的SDL本身不支持Listener，所以需要一个监听线程做转换（SDL事件部分基于WinAPI） @Miigon

**Comment by Miigon** [comment]
为何这么麻烦
获取了输入直接指派一个函数处理，然后那个函数充当转换和分配
我指的listener是游戏和插件API层面的

**Comment by DWVoid** [comment]
@Miigon SDL是监听式的事件处理，所以事件一定会占用主线程，这是由于操作系统的历史遗留问题导致的，并不是指派那么简单

**Comment by Miigon** [comment]
事件循环，这个是必须的，但是并不会影响渲染，而且当渲染卡住了，输入也没必要继续运行了，因为进行也没有意义，渲染也无法做出回应，放到一个线程正好

**Comment by Miigon** [comment]
而且，在单核cpu上，这会适得其反

**Comment by DWVoid** [comment]
事件处理参见 https://github.com/Infinideastudio/Infinideastudio-Frameworks/blob/0.0.1-Adjust/UILIb/src/uicore.cpp#L337 ，这是SDL处理的唯一方式，较GLFW而言复杂不少，但是提供了较高的自由度

**Comment by DWVoid** [comment]
单核双逻辑处理器吗？但是NW就本身而言至少三个线程

**Comment by ghost** [comment]
**(旁观人员，纯胡扯)**

建议线程数量做的少一些，调试会更方便，遇到多线程的heisenbug造成的horror debugging会少一些，而且像Miigon所说，在单核处理器上，线程调度很尴尬啊。

**Comment by DWVoid** [comment]
不过渲染的层面你们自己也要做一下限制，当FPS连续长时间低于1的话就需要减小处理压力了，我暂且同意将渲染放到主线程上作为空闲函数对待

**Comment by DWVoid** [comment]
关于另外一点就是大规模采用std::future处理事件是否合适，因为据我所知某些事件的处理时间相对长，可能需要并发处理

**Comment by Miigon** [comment]
异步处理吗？“某些事件”指的是API调用？

**Comment by ghost** [comment]
然后又要考虑可重入问题了?

**Comment by DWVoid** [comment]
最明显的就是resize，因为需要重写计算所有控件的位置，分配行列大小

**Comment by Miigon** [comment]
但是“没计算完就渲染而得到resize前的结果”和“渲染卡顿”给玩家带来的感觉都是同样的：程序卡顿了
异步和多线程带来的问题可能会比解决的多。。。

**Comment by DWVoid** [comment]
同意

**Comment by Miigon** [comment]
那就暂定把渲染放在主线程事件处理后了？

**Comment by DWVoid** [comment]
@Miigon 是的。因为刚注意到MS在处理WPF的时候也是这样做的。
另外，自动布局以及控件嵌套确实是一个值得讨论的问题https://github.com/Infinideastudio/Infinideastudio-Frameworks/issues/10
到这里讨论吧

**Comment by ascchrvalstr** [comment]
(旁观人员，纯胡扯)
个人认为放主线程比较吼

**Comment by Miigon** [comment]
ok，结果：
- 布局方式不需要任何的改变，只需要提供更多的简化接口即可
- UI层面提供framework
- 渲染放在主线程事件处理后
