### ISSUE TITLE
The coding style is so anti-social

### ISSUE THREAD

**Issue by DWVoid** [Infinideastudio/NEWorld#6]
代码及其混乱，完全没有发挥C++的class应有的优势，维护及其困难
需要所有人手对现有代码进行整理

**Comment by ghost** [comment]
欢迎加入希修斯工程。

**Comment by ghost** [comment]
能给一个联系方式吗？

**Comment by DWVoid** [comment]
普通情况可以给我发邮件：yshliu0321@icloud.com ys_37677@126.com 着急的话可以给我发短信：+8613661562452，上海的号码

在 2016-03-21 21:57:54，"D Laboratory" notifications@github.com 写道：

能给一个联系方式吗？

**Comment by ascchrvalstr** [comment]
代码整理极其困难

**Comment by DWVoid** [comment]
@ascchrvalstr  很正常。长期以来代码风格就不太友善

**Comment by ascchrvalstr** [comment]
@DREAMWORLDVOID 你正在使代码风格变得更不友善

**Comment by ascchrvalstr** [comment]
另外你直接commit到0.5.0是不对的

**Comment by ascchrvalstr** [comment]
并且你还违背希修斯的规则，加入了新功能

**Comment by ascchrvalstr** [comment]
并且你和@dtcxzyw 写出了大量低质量代码

**Comment by ascchrvalstr** [comment]
write权限不想要了吗

**Comment by ascchrvalstr** [comment]
那好，我现在就取消

**Comment by HydroH** [comment]
[**@ascchrvalstr**](https://github.com/ascchrvalstr) commented on [2016年4月8日 GMT+8下午6:00](https://github.com/Infinideastudio/NEWorld/issues/6#issuecomment-207356508):

> 那好，我现在就取消

说话请一口气说完……这不是即时聊天软件，订阅了此repo的人会一下收到很多邮件，令人很困扰的

**Comment by DWVoid** [comment]
话说这是什么情况，怎么突然发飙了。。。

在 2016-04-08 18:00:01，"Bruce Dai" notifications@github.com 写道：

并且你和@dtcxzyw 写出了大量低质量代码

**Comment by ghost** [comment]
没有必要因为这些“代码”让自己变得非常生气，不值当。

**Comment by ascchrvalstr** [comment]
但是这不是一个正常的项目，而是一个濒临死亡的项目

**Comment by ascchrvalstr** [comment]
已有相同主题issue
