### ISSUE TITLE
chunkLoader编译出错

### ISSUE THREAD

**Issue by Miigon** [Infinideastudio/NEWorld#60]
src/client/neworld.cpp.o：在函数‘Application::beforeLaunch()’中：
neworld.cpp:(.text+0x11e8)：对‘ChunkLoader::build(int) const’未定义的引用
libnwshared.a(pluginapi.cpp.o)：在函数‘nwRegisterChunkGenerator’中：
pluginapi.cpp:(.text+0x280)：对‘ChunkGeneratorLoaded’未定义的引用
pluginapi.cpp:(.text+0x2da)：对‘ChunkGeneratorLoaded’未定义的引用
pluginapi.cpp:(.text+0x2e4)：对‘ChunkGen’未定义的引用

在 [FIRST CHUNK, FULL OF ROCKS!!!!!!!](https://github.com/Infinideastudio/NEWorld/commit/29c42bac2a764b863491a5d87e8cc49799a3e4d8)
pluginapi.cpp是被归类到client中编译的

**Comment by bridgekat** [comment]
pluginapi放进shared啊。。。

**Comment by bridgekat** [comment]
chunkloader也是shared

**Comment by Miigon** [comment]
你在物理路径上没有改？

**Comment by Miigon** [comment]
不，按照直接pull下来还是失败了

**Comment by Miigon** [comment]
pluginapi.cpp中的ChunkGen和ChunkGenerator是什么鬼，难道是全局变量？
在linux下static库没有办法直接访问link它的程序的全局变量

**Comment by bridgekat** [comment]
wtf
我写这几个全局变量只是为了测试的……后面会改掉的
你先看看有没有其他解决办法

**Comment by qiaozhanrong** [comment]
wtf
我写这几个全局变量只是为了测试的……后面会改掉的
你先看看有没有其他解决办法

**Comment by Miigon** [comment]
@qiaozhanrong wtf
你写测试也别用全局变量啊……万一忘了改呢
我怎么知道有没有其他解决办法，你的代码太梦幻啊
我cscope都没能找到ChunkGen在什么文件里

**Comment by bridgekat** [comment]
ChunkGen在chunkloader.cpp里

**Comment by bridgekat** [comment]
你先把全局变量的赋值和取值写成函数试试？
