### ISSUE TITLE
关于Texture和UI::Base::Texture的取舍

### ISSUE THREAD

**Issue by Miigon** [Infinideastudio/NEWorld#63]
@DREAMWORLDVOID @abc612008 @qiaozhanrong 
客户端的`Texture`和UILib的`UI::Base::Texture`在功能上重合，前者实现更具体
但是后者是Uilib提供的，且两者在客户端中被混用，在最终融合进Uilib的前提下，请求取舍建议。

**Comment by DWVoid** [comment]
UIL0.0.2(aka Presentation Framework 0.0.2)完成之前保留两者

**Comment by Miigon** [comment]
顺带一提，我的重构在NEWorld仓库中修改了大量的UILib代码
在你那边完成之后移动过来时不要直接覆盖，UILib的代码除了Logger外我会尽量不做任何改动

**Comment by Miigon** [comment]
@DREAMWORLDVOID 
希望把Grid和Control合并成为Element
关于层级的问题，希望_不要_使用std::shared_ptr，这个东西可能会导致写代码的时候变得更随意导致内存泄露

我的想法是，由于同一个元素实例不可能在屏幕上存在两个实例，也不可能存在两个父，所以干脆只允许内部创建Element，外部只能获取，这样能保证每个元素都有父，并且归根到总父元素`root`，为每个元素命唯一名，通过父元素可以获取其拥有的子元素，或者从`root`元素可以树状获取所有的元素。

大概可以这么写：

``` c++
Element *Element::newChild(std::string name)
{
  Element *e = new Element(name);
  m_children[name] = e;
  e->setParent(this);
  return e;
}

void Element::removeChild(Element *child) // Only called in child element's destructor
{
  // do something to remove child from m_children
}

Element::~Element()
{
  m_parent.removeChild(this);
  for(auto &e : m_children)
  {
    delete e;
  }
}

class Window : Element; //Window is also an element,but it's not able to create by the user but the "createWindow()" function.
class Button : Element;
class ImgBox : Element;
Window *win = createWindow("MainWin");

int main()
{
  Button *startButton = win->newChild("startButton");// 位置：root.MainWin.startButton
  startButton->setPos(100,100);
  ImgBox *startButtonImg = startButton->newChild("bgimg"); // 位置：root.MainWin.startButton.bgimg
  startButtonImg.setImage("./abc.png");
  delete startButton; // 同时释放startButton和startButton.bgimg
}
```

也就是说，和图片资源一样，使用内部统一管理，外部只能使用，不能自己创建和加载
这才是一个框架该有的样子 @qiaozhanrong

**Comment by DWVoid** [comment]
@Miigon 其实采用shared_ptr有另外的考虑，是一种比较特殊的情况) 
`dc=getchild(x)`
`dosomething1(dc)`
`dosomething2(this)//外部函数，行为不确定`
`dosomething3(dc)`
这个逻辑上没有任何问题，但是一旦外部函数值一旦删除了这个对应的控件，按照你的方法这个对象就被销毁了，最后一个函数的访问就会出错，基本上后果就是程序崩溃

**Comment by DWVoid** [comment]
@Miigon 大概看了一下你的思路，和我的基本一样，就是font的搜索别做大修改，因为这部分基本直接废掉了

**Comment by Miigon** [comment]
@DREAMWORLDVOID 析构函数private应该就能保证安全了
如果所说的“外部函数”真的想破坏内存也无法真正阻止
我先不做修改，你先写吧，你写完我再看看有什么可以改

**Comment by Miigon** [comment]
@DREAMWORLDVOID 在控件和回调函数方面希望能动态查找，并且支持多回调
即是用`map <string, Element> controls`和`map <string, list<function>> callbacks`来存储
效率要求高的，如绘画事件，再考虑添加原生接口
因为这么做的话，不仅对插件友好，且将来要导出PluginAPI能减少不少麻烦

例如，一个插件要为NW原生的Button添加一个事件处理函数`onJoystickPressed`，如果是原生C++类函数来实现的话就没办法实现了。（听说boost::signals2就是做这事情的？）

而控件库就自不用说了，动态添加全靠它，可以省一大堆派生类，全部使用Element来实现各种button、imgbox、label、input、scroll，而且只有这样才能支持PluginAPI封装。

我会实现一个`Container`类，用来描述父子包含的数据的树状关系的容器，用法大概会是和我上面提到的预想的Element差不多的：

``` c++
Container<std::string> *root = Container::makeRoot<std::string>();
Container<std::string> *c = root->addChild("MainWindow");
c->setData("DATA MAINWINDOW");
c->addChild("Button1")->setData("DATA IN BUTTON 1");
c->addChild("Button2")->setData("DATA2");


root->at("MainWindow")->getData(); // "DATA MAINWINDOW"
root->at("MainWindow")->at("Button1")->getData(); // "DATA IN BUTTON 1"
root->at("MainWindow")->at("Button2")->getData(); // "DATA2"

delete root; // will also delete all the children of it (include MainWindow) automatically.
```

这个类可以用来为controls分类防止不同插件名称冲突 和 作为界面包含树来使用，将来也可用来为方块分配名称空间

你觉得怎么样？

**Comment by ascchrvalstr** [comment]
1. 用红黑树来存储这些东西真的有必要吗
2. function是类模板，list<function>根本不可行
3. **因为游戏的界面相对固定**，所以可以采用如下的方法存储子控件

``` C++
template<typename... SubControls>
class Window
{
public:
    std::tuple<typename SubControls...> subControls;
    template<size_t i>
    // get the child in index i
};
```

（仅供演示）

**Comment by DWVoid** [comment]
@ascchrvalstr 完全反对。你这个方法完全破坏了GUI应有的动态。另外，既然是容器，完全可以通过重载[]来实现查找功能，并且可以通过.来分隔以实现嵌套的寻址（这个我以前实现过，还是蛮好做的）

**Comment by DWVoid** [comment]
@Miigon 关于函数的问题不用那么麻烦，plugin可以通过传统函数指针的方式指定回调（其实我更期待plugin直接访问Cpp接口）

**Comment by DWVoid** [comment]
另外，关于容器的想法我略微不同。我的意思是以UIElement作为基类，提供事件和渲染等基本接口，然后派生三个控件类：control（单容器类），canvas（简单布局容器），grid（复杂布局容器），content类型均为element

**Comment by DWVoid** [comment]
``` C++
        class UILIB_API Control
        {
        public:
            std::string xName;  //ID
            Margin cMargin;     //Position Data
            size_t gridPosX, gridPosY;

            Control() = default; //Creator
            Control(std::string _xName, Margin _Margin);
            virtual ~Control() = default;

            virtual void setSize(size_t x, size_t y);
            virtual void parentResize(Grid* parent);
            //Event Handlers
            virtual void render();
            virtual void onResize(size_t x, size_t y);
            virtual void onParentResize(Grid* parent);
            boost::signals2::signal<void(FocusOp)> focusFunc;
            boost::signals2::signal<void(int x, int y, int dx, int dy)>mouseMove;
            boost::signals2::signal<void(MouseButton, ButtonAction)> mouseButtonFunc;
            boost::signals2::signal<void(CursorOp)> cursorEnterFunc;
            boost::signals2::signal<void(double, double)> scrollFunc;
            boost::signals2::signal<void(int, ButtonAction)> keyFunc;
            boost::signals2::signal<void(CInpArgs e)> charInputFunc;
            boost::signals2::signal<void(const char*)> dropFunc;
            boost::signals2::signal<void(int x, int y, ButtonAction action)> touchFunc;
            boost::signals2::signal<void(int x, int y, int dx, int dy)> touchmove;

            bool enabled, mouseOn, pressed, focused;
        };
```

这是现在control的定义，处理事件方面只有resize还没有采用多回调，因为有一点小问题（内部实现有点混乱 @Miigon

**Comment by ascchrvalstr** [comment]
以及我不怎么喜欢虚函数之类的玩意儿，静态多态是坠吼的
你搞的这个UILIb啊，excited

**Comment by DWVoid** [comment]
@ascchrvalstr 你那样做会莫名其妙的拖慢编译速度，生成大量的binary而且极大程度的降低了代码的可维护性以及可读性，自己衡量一下得失吧（因为这个写法意味着大量的模版元编程而且工程及其复杂

**Comment by DWVoid** [comment]
而按照现在的想法，虚函数应该只有3个:dtor，render(), operator [ ]

**Comment by DWVoid** [comment]
我只能说你玩模版玩的走火入魔了，什么都想用模版搞，完全不记后果（你考虑过外部UI图形化设计器这种东西吗？），exciting

**Comment by Miigon** [comment]
@DREAMWORLDVOID 其实你的想法和我最初的一样
但我之后说的Container的实现是出于保证控件类只能从内部来构造（保证指针安全，少用std::shared_ptr）出发的

要为Container添加子Container被限定只能使用`addChild()`，为了达到这一点，我需要把构造函数设定为private，且析构函数必须做从父类删除自身，还有删除所有子类的工作，但是作为private的话继承于它的类就懵逼了，即使是protected，也很难保证子类一定会去调用父类的构造和析构函数（要是遇到了拙劣的开发者）。

基于这点考虑，我干脆把Container作为包含树单独分离出来，不让其他类继承它，改为让其存储需要存在树状关系的类（就像链表节点那样）。

而关于回调方面，上面说到的Control的代码：

``` c++
boost::signals2::signal<void(FocusOp)> focusFunc;
boost::signals2::signal<void(int x, int y, int dx, int dy)>mouseMove;
boost::signals2::signal<void(MouseButton, ButtonAction)> mouseButtonFunc;
boost::signals2::signal<void(CursorOp)> cursorEnterFunc;
boost::signals2::signal<void(double, double)> scrollFunc;
boost::signals2::signal<void(int, ButtonAction)> keyFunc;
boost::signals2::signal<void(CInpArgs e)> charInputFunc;
boost::signals2::signal<void(const char*)> dropFunc;
boost::signals2::signal<void(int x, int y, ButtonAction action)> touchFunc;
boost::signals2::signal<void(int x, int y, int dx, int dy)> touchmove;
```

这么做的话，作为一个插件要修改其中的值就很麻烦了，不希望看到为每个属性添加一个set接口的局面，而且这样如果添加了新的属性的话，难道要再去添加新的插件接口？而动态存储的话，不仅不存在这个问题，而且还能实现为NW原生的组件添加新属性。

现在的实现还有一点问题，那就是主窗口，现在的主窗口的做法是定义一个`class MainWindow : public Window`，我怕的是，这样会大大提高对C++语言特性的依赖性，导致通用性大幅降低，而且导致一个什么SubWindow之类的也要弄一个新类，而插件想创建新窗口就没门了
更好的方法是把基本的类实现，并实现得足够通用，做到基本的工作可以完全胜任，要添加新组件可以用基本组件拼装（包括窗口类），这一点我看到其他一部分类已经做到了

剩下的，我还在思考的问题是，插件拼装起来的类怎么实现比较好，例如一个插件提供了一个XButton，作用是用图片来作为按钮的文字

那么这个插件需要一个原生Button，还有一个原生ImageBox
问题就在于，怎么组织这两个组件
当然如果要把ImageBox的鼠标处理事件传递给Button（这样才能使点击图片也能触发按钮，不“遮挡”），最自然的还是把ImageBox作为Button的子组件，然后ImageBox中的事件回调调用父组件，但如果其他使用这个类的地方删除了ImageBox的话，就可能导致出错，也可能导致子组件重名之类的问题
（当然也可能是我杞人忧天了，一般类自己添加的组件只有自己会用）

**Comment by Miigon** [comment]
总的来说，Container的设计是为了解决指针安全性方面的问题（shared_ptr永远不是解决方案，他使软件不会崩溃，但带来的内存问题可能更多），还有为了对Container的接口的更改不至于影响到派生类（比如接口重名），而考虑的在每个Container中存指向类的指针而不是派生出类

如果想要Container中只能存储某个类，比如Element（不是Container的派生类），也可以写成模板类

**Comment by ascchrvalstr** [comment]
搞个Tk式的接口不行吗...（在构造子控件的时候把父控件的指针什么的传进去）
析构的时候父类删除子类

**Comment by Miigon** [comment]
@ascchrvalstr `在构造子控件的时候把父控件的指针传进去`和`析构的时候父类删除子类`本身就不是匹配的东西吧
万一创建子控件的那段代码是某个2b写的，还自己偷偷留了一份自己用呢？他就会发现自己的代码里有new没有delete，但是控件还是无缘无故变成野指针了。

而我这么做的目的就是，为了告诉开发者：“这个对象不是你new的，不应该由你来delete，我什么时候会delete，由我决定”，这样就使得开发者在需要使用的时候要去getChild，防止错误的理解和使用导致的崩溃。

std::shared_ptr虽然可以解决这个问题，但傻逼开发者同理
效率开销的话，对于查个表这点我觉得基本可以忽略了，反正也要做成动态，没法避免

**Comment by Miigon** [comment]
@DREAMWORLDVOID 如果你没有太多时间的话，可以把你的想法告诉我，我有比较充裕的时间来实现和探讨。
毕竟我从开重构坑之后已经恐吓 @qiaozhanrong 别加代码了hhh 不想成为别人的累赘

**Comment by DWVoid** [comment]
@Miigon 如果你有多余的时间的话可以考虑先把两个texture合并了（主要是可选的mipmap）。我这边还在尝试不同的结构，减小代码的复杂度

**Comment by DWVoid** [comment]
@Miigon 窗口用继承类的写法是各个UI库的惯例，这样可以增加代码的可读性和降低维护难度（一般的做法是如果控件在接下去的代码中会被引用，那么创建的时候保留一个handle在继承类里面，方便访问）（因为某些窗口会很复杂），当然直接用window类创建窗口并不是不可以，而是不推荐（比如一个子窗口关闭以后一个巨大无比的对象组没有销毁这种事极有可能发生）。子父控件的事情之前已经说了，不让控件向上级访问就算为了避免这种情况。就你那个XButton的例子而言，正确的做法是应该将Image对象作为button的子控件，并且使XButton继承自button，这样不论是点击图片还是图片外的按钮区域事件都会被按钮截获，也就不存在问题了

**Comment by Miigon** [comment]
但这个库不能完全说是UI库，也要考虑以下NW的实际情况
NW的PluginAPI是最大的麻烦，这东西必须最大兼容

还有一点让我感到很难以释怀的，就是Texture，如果两个合并的话，就会出现NW使用了`UI::Texture`做了UI渲染之外的事情

**Comment by ascchrvalstr** [comment]
@Miigon 难道父类析构完了子类还要手动删除？很多GUI库不都是子类构造传父类指针吗？
另外，难道应该被删除的控件不删除，让ub的代码还能正常跑的库是一个吼的库吗？

**Comment by Miigon** [comment]
@ascchrvalstr 当然不是，但这样会导致有new没有delete的代码出现
代码又不是写给计算机看的，要是只要能跑就可以，为什么不直接写机器码？

**Comment by bridgekat** [comment]
在构造子控件的时候把父控件的指针什么的传进去，然后析构的时候只在父控件的children中删除自己，而不管子控件呢？【啥也不懂，瞎扯的

**Comment by Miigon** [comment]
@qiaozhanrong Memory leak

**Comment by bridgekat** [comment]
@Miigon 让new出控件的人来delete啊。。。就跟很多指针操作一样

**Comment by bridgekat** [comment]
另外觉得用UI::Texture不适合在NW里用的话也可以就写两个Texture类吧。。。重复就重复，至少代码表达的意思上更说得通【什么鬼

**Comment by Miigon** [comment]
Texture的问题我是偏向于支持两个的，或者说UI里的不应叫做Texture，外部统一使用UI::Image来读入图片，而UI::Texture由UILib负责生成，外部不可用（也无需可用）

**Comment by Miigon** [comment]
@qiaozhanrong 
所以我说的这么麻烦就是为了不让哪个傻缺用完不delete啊
而且还可能存在某个控件的父控件已经销毁了它还在用那个控件

**Comment by bridgekat** [comment]
额。。。那就用你说的方法吧

**Comment by bridgekat** [comment]
Texture的话我觉得在UI里创建Image的时候指定一个图片文件路径，UI用内部的Texture啥的去加载然后显示，不属于UI的Textures加载都写到NW里？

**Comment by DWVoid** [comment]
同意。将Texture仅作为Image在显存的对象句柄

**Comment by Miigon** [comment]
不属于Ui的texture都用NW版本的texture实现
主界面的背景、按钮背景图、图片框这一类就用UI::Image

**Comment by bridgekat** [comment]
对

**Comment by Miigon** [comment]
不过我刚刚试着写过了，果然界面控件还是外部new内部delete比较方便
就按照 @DREAMWORLDVOID 一开始想的那样写吧

**Comment by ascchrvalstr** [comment]
有new没有delete的代码太多了...
shared_ptr<T>不就是吗？（不用make_shared）
你怎么不去质疑shared_ptr

**Comment by harrynull** [comment]
@ascchrvalstr shared_ptr怎么了？哪里没delete了？

**Comment by bridgekat** [comment]
他的意思是使用shared_ptr时不用显式调用delete

**Comment by harrynull** [comment]
内部不也用了吗……

**Comment by bridgekat** [comment]
是啊，他的意思是控件也搞个外部new内部delete，然后Miigon觉得这样不好

**Comment by ascchrvalstr** [comment]
如果分配和释放在同一个堆的话是不会出问题的

**Comment by bridgekat** [comment]
虽然可能不出问题但是@Miigon 觉得逻辑不好

**Comment by Miigon** [comment]
随便了，反正我承认我的提议会提高复杂度，就用外部new内部释放的方式吧

**Comment by bridgekat** [comment]
额
