### ISSUE TITLE
我们的优化可能已经落后于Minecraft 1.10.2了。。。

### ISSUE THREAD

**Issue by bridgekat** [Infinideastudio/NEWorld#65]
NEWorld Alpha 0.5.0 Preview 20160205在FPS上已经与Minecraft 1.10.2（Java8 64bit，2GB内存）相差无几了。。。虽然说一个是32bit一个是64bit，可能有些差距，但是也要考虑jre本身执行效率就比native code慢，而且现在相差已经不多了。。。个位数了。。。
所以说重构啥的快点弄吧。。。在代码结构上纠结了这么长时间。。。

**Comment by ascchrvalstr** [comment]
> jre本身执行效率就比native code慢

请问哪篇文章这样说的？jre的内存分配什么的，比`operator new`不知道高到哪里去了
第二，优化**根本不应该被一个成熟的游戏开发者放在首位**。

**Comment by Miigon** [comment]
重构目前丢给了 @DREAMWORLDVOID 搞，但。。。杳无音讯
总之，雕琢前先有原型，希望能在保证质量的前提下看到原型

你说Hotspot VM的话，JIT的效率在一些方面比C++高
最差的也不会差太远

**Comment by DWVoid** [comment]
重构我只管UI，NW交给你们了 @Miigon 本来游戏逻辑就是qiao和null的事情，我的想法和他们不太合拍

**Comment by DWVoid** [comment]
如果内存频繁分配的话还是搞memory pool，而且本来就应该兼容64bit，只选择32bit是你们的事情

**Comment by DWVoid** [comment]
UI的话新构架的第一个原型就是已经上传的Canvas（uicontainer.cpp),因为某些组件要重写所以没有完成，我需要重写变幻矩阵

**Comment by Miigon** [comment]
不过没有UI，几乎什么都做不了了
游戏部分的重构无非就是几个类架构改来改去
而MainWindow和MainMenu(pages.cpp)我都有重写的冲动了，硬编码的UI布局。。。

**Comment by bridgekat** [comment]
@ascchrvalstr 只有个new比C++快，你也知道他的new是基于内存池的，我们要是弄内存池理论上可以把这点差距补回来

**Comment by bridgekat** [comment]
> 第二，优化根本不应该被一个成熟的游戏开发者放在首位。

我没说放在首位，主要是因为NW以前最大的特点就在于优化，我们不应该让这个特点消失啊。。。

**Comment by DWVoid** [comment]
@qiaozhanrong 内存管理的话貌似和系统比较有关系。同样的程序OS X的clang7编译运行只用了16.7MB内存（64位debug），在Win10下面VC140编译运行（release x86）居然用了58MB。我怀疑可能和在堆上分配大量的小内存片段有关

**Comment by Miigon** [comment]
@DREAMWORLDVOID @qiaozhanrong 总之别冲动，现在先暂时直接系统调用alloc，将来发现瓶颈了再改
不要过早的优化，将来要全局优化碍手碍脚
话说 @abc612008 不是已经写过内存池了么？

**Comment by bridgekat** [comment]
他写的内存池暂时没有放到NW里，我也赞成现在先不用内存池，结构确定之后再用。。。
只是说现在在注重结构的优雅程度时也要顾及一下效率问题。。。（PS：没说现在效率不行）

**Comment by DWVoid** [comment]
话说 @Miigon UI的话帮忙看一下uicontainer.h里面的接口，主要是插入，删除，访问的函数是不是要加以及要重载哪几个操作符（硬编码的问题稍安勿躁，等结构确定以后加一个xml解析器，前提是要有人帮忙）

**Comment by Miigon** [comment]
@DREAMWORLDVOID Element依然没有容器功能嘛。。
[这是我自己的container实现](https://github.com/Miigon/Ascui/blob/master/src/container.h)
而我的Element继承了Container类
由每个窗口提供一个root container，通过这个root可以寻路到所有container上
而我这里用了普通指针，而不是shared_ptr
因为这里遵循了`共享不修改，修改不共享`的原则，这个指针**只有**不被共享才能保证安全
如果这个组件销毁了，外部也不应该保留有它的引用，如果用了shared_ptr来掩盖这个问题，这个问题就会很难被找到
所以这个trade off我选择了安全和灵活而不是效率

**Comment by ProgrammerZSQ** [comment]
@DREAMWORLDVOID 然而占用内存大小不同并不仅仅是和系统的内存管理有关吧。。。应该还有编译器的一些因素在里面

**Comment by bridgekat** [comment]
还有运行库和编译优化的原因，反正原因很多

**Comment by Miigon** [comment]
@ProgrammerZSQ 占用内存大小编译器的因素倒是不大，可以尝试以下用gcc编译，会发现占用内存没少多少，大块的应该是MSVCRT的问题

附带我的机子的结果：
Ubuntu 16.04 LTS 64bit
gcc6.1 -O2

22.5MB内存占用

@DREAMWORLDVOID OS X的16.7MB内存可能是因为OSX有内存压缩，或者libc占用较少

**Comment by DWVoid** [comment]
@Miigon Element不提供容器是因为你和我对element的定义有差别导致的。对我来说element只是元素，任何种类的UI元素，而容器控件也是一种元素。（否则某些基础元素的开销会很大，比如一个矩形）

**Comment by Miigon** [comment]
所以你的Element是比Container更底层的，和我相反？
也对，点线面不应该被作为容器

**Comment by jacky8399** [comment]
> 我没说放在首位，主要是因为NW以前最大的特点就在于优化，我们不应该让这个特点消失啊。。。

所以NEWorld將來就沒有新特性了
可以 這很新創無際

**Comment by taxerap** [comment]
@jacky8399 “毫無意義的優化”不是特性的一種麼233

**Comment by harrynull** [comment]
泥们垢了啊
