### ISSUE TITLE
关于本游戏的发展路线

### ISSUE THREAD

**Issue by Miigon** [Infinideastudio/NEWorld#66]
希望讨论一下这个游戏在内容计划上的未来发展路线
大致分为：
1. 游戏可以和Minecraft一样本身自带大量游戏元素，拥有大量的方块、生物、物品等，拥有完善的系统，而Plugin只是作为对原始内容的补充。
2. 游戏和Minetest一样本身不提供任何元素，包括方块、生物、物品等，但是包含对应的系统，所有内容通过Plugin的形式提供。

我是支持后者的，因为后者会迫使编写可扩展、定义良好、效率高的PluginAPI，并且相比Minecraft那种随处都是硬编码的代码，后者会更好维护和扩展。

**Comment by ascchrvalstr** [comment]
滋瓷第二种，但是我怀疑这项目最缺的是开发效率

**Comment by Miigon** [comment]
@ascchrvalstr 追快速成型不断迭代的，不就是那个最开始的NW么？而现在在重写，重写的目标不会和重写前一样吧？

**Comment by Miigon** [comment]
@ascchrvalstr 你有这种感觉完全是因为我们前期折腾了太多的轮子了，比如Logger，比如UI

**Comment by bridgekat** [comment]
滋磁第二种

**Comment by ProgrammerZSQ** [comment]
支持第二种，原版MC的优化大家都知道（虽然现在快赶上了=_=），不应该继续写出原版MC那样~~简洁~~糟糕的代码

**Comment by harrynull** [comment]
vote 2

**Comment by Miigon** [comment]
@Infinideastudio/cppgroup

**Comment by riteme** [comment]
当然是支持第二种啊，毕竟第一种要么硬编码，要么就是利用第二种的接口来提供官方扩展。  
硬编码因该是不会被接受的。
