### ISSUE TITLE
花括号换行 or 不换行

### ISSUE THREAD

**Issue by SuperSodaSea** [Infinideastudio/NEWorld#7]
请求确定

**Comment by ghost** [comment]
基本法来看是要换行的

**Comment by Code-017** [comment]
我觉得循环不换，普通的换

发自我的 Windows Phone

---

发件人: D Laboratorymailto:notifications@github.com
发送时间: ‎2016/‎3/‎19 21:23
收件人: Infinideastudio/NEWorldmailto:NEWorld@noreply.github.com
主题: Re: [NEWorld] 花括号换行 or 不换行 (#7)

基本法来看是要换行的

---

**Comment by WenceyWang** [comment]
我觉得除了一行的方法都应该换行

**Comment by WenceyWang** [comment]
我觉得除了一行的方法都应该换行

**Comment by ghost** [comment]
所以这是一场圣战

**Comment by bridgekat** [comment]
@DLaboratory 不换行大法好

**Comment by bridgekat** [comment]
【其实我两个都不反对

**Comment by ghost** [comment]
@qiaozhanrong Allman/BSD大法好，打到K&R和Stroustrup牛鬼蛇神！

**Comment by taxerap** [comment]
不换！！！！！！！！！！！

**Comment by ascchrvalstr** [comment]
换！Allman(ANSI)大法好！打倒某Java Style！

**Comment by idkidknow** [comment]
做个投票不就好了……

**Comment by bridgekat** [comment]
@idkidknow 已经准备投票了

**Comment by ascchrvalstr** [comment]
现在争论已经没有意义了

**Comment by charlesdong** [comment]
换！！！
我就喜欢
if (cond)
{
...
}
不喜欢
if (cond) {
...
}
更不喜欢
if (cond) {
... }

**Comment by jacky8399** [comment]
@CharlesDong 都close了你還回覆什麼啊……[開發者規範](https://github.com/Infinideastudio/NEWorld/blob/renew/doc/regulations.md)都寫了要用`Allman/BSD`了
