### ISSUE TITLE
工程“互斥锁”明确

### ISSUE THREAD

**Issue by harrynull** [Infinideastudio/NEWorld#70]
@Miigon @DREAMWORLDVOID 
望明细个人正在制作的容易导致冲突的部分（加“互斥锁”的部分）

**Comment by Miigon** [comment]
我在等UI
顺便在写网络解包，还有试试raknet

**Comment by bridgekat** [comment]
结构重组你还在弄吗

**Comment by Miigon** [comment]
等UI嘛

**Comment by harrynull** [comment]
@Miigon 那现在能不能搞结构？

**Comment by Miigon** [comment]
小懒。。怕被喷

**Comment by harrynull** [comment]
@Miigon 我说我能不能搞NW了……

**Comment by Miigon** [comment]
@abc612008 你先做吧，不和前面开过的几个issue里说的有冲突就没问题
不过涉及使用UI的部分，因为 @DREAMWORLDVOID 说了会改接口，所以做了也没用

**Comment by harrynull** [comment]
@Miigon 前面开过的几个issue主要指是？

**Comment by Miigon** [comment]
@abc612008 大多是关于Ui的，写游戏内容部分也没有必要过分在意，只是记得，UI::Texture不要用来做3D里的Texture
还有，GameView改名，如果不同Manager之间需要互相调用，不要直接向Application获取或者弄全局，而是把实例引用传递过去

**Comment by harrynull** [comment]
@Miigon get
