### ISSUE TITLE
关于类层次结构的疑问

### ISSUE THREAD

**Issue by harrynull** [Infinideastudio/NEWorld#72]
Application, GameScene, BlockManager, PluginManager, WorldManager, ChunkPointerArray,Player,Texture, ChunkRenderer, World, Chunk这些类的包含关系？
@Miigon @qiaozhanrong

**Comment by bridgekat** [comment]
不清楚

**Comment by Miigon** [comment]
我说一下我自己的设想：
　
![nw-classes-structure](https://cloud.githubusercontent.com/assets/16161991/17917331/f040d3de-69ed-11e6-8a34-8c67c5493751.png)
　　
绿色为实例，灰色为定义，箭头表示调用
画图技术太菜，我也没指望别人能看懂，大概就是所有的Manager和Renderer都是和GameScene同级别的
总之我不喜欢这个GameScene，产生的问题比解决的问题多

**Comment by harrynull** [comment]
卧槽一言不和就甩示意图

**Comment by harrynull** [comment]
@Miigon 有个问题就是ChunkRenderer和Chunk是一一对应的

**Comment by Miigon** [comment]
ChunkRenderer是做什么的

**Comment by Miigon** [comment]
一个画一个Chunk？

**Comment by harrynull** [comment]
@Miigon 对，用来生成chunk的VAO，一个简单的包装，一对一的

**Comment by Miigon** [comment]
干脆存在Chunk里？感觉也不是很好呀。。

**Comment by Miigon** [comment]
这部分我没记错的话是 @qiaozhanrong 写的？

**Comment by harrynull** [comment]
@Miigon 是

**Comment by harrynull** [comment]
@Miigon qiao最近看上去很忙，我先帮他做一些

**Comment by harrynull** [comment]
@Miigon 但是我还是觉得BlockManager和WorldManager应该放在GameScene里，因为只有GameScene会访问这两个类

**Comment by harrynull** [comment]
@qiaozhanrong @Miigon 
按照我的理解修改了下结构，请review
以及：WorldRenderer应该在哪里（不能在World里）

**Comment by bridgekat** [comment]
我还好啊

**Comment by bridgekat** [comment]
@Miigon 辣个图怎么画的

**Comment by bridgekat** [comment]
BlockManager直接放Application里面，加载方块类型应该在程序开始时进行

**Comment by harrynull** [comment]
图里不就是放application里的吗

**Comment by Miigon** [comment]
WorldManager放到GameScene里是对的
但BlockManager就如 @qiaozhanrong 说的一样，启动时就要加载，并且插件也应该在启动时添加自定方块，所以最好application
不管是WorldRenderer还是ChunkRenderer都是和World和Chunk有一一对应的关系,，内部存引用
WorldRenderer放在GameScene里，ChunkRenderer(s)放在WorldRenderer里怎么样
由于每次只会有一个World被渲染，所以每次维护一个CurrentWorld的Renderer就好了

**Comment by harrynull** [comment]
@Miigon 那么就是WorldRenderer和WorldManager都放Scene里？

**Comment by bridgekat** [comment]
WorldRenderer和WorldManager不会同时出现在一个程序里辣
客户端是WorldRenderer+World，服务端是WorldManager

**Comment by harrynull** [comment]
woc，说的好像很有道理OAO!
那client其实就不需要WorldManager了？

**Comment by bridgekat** [comment]
对啊

**Comment by Miigon** [comment]
客户端需要一个World(shared)实例，存当前世界的信息
