### ISSUE TITLE
补充插件的CMakeLists.txt

### ISSUE THREAD

**Issue by harrynull** [Infinideastudio/NEWorld#75]
使用CMake的时候插件没被生成

**Comment by bridgekat** [comment]
插件CMakeLists和主程序CMakeLists分开吧，然后用个.sh生成主程序再生成插件

**Comment by harrynull** [comment]
@qiaozhanrong 为啥

**Comment by bridgekat** [comment]
不然有人只想编译主程序就比较麻烦

**Comment by harrynull** [comment]
@qiaozhanrong 只编译主程序有卵用啊……

**Comment by bridgekat** [comment]
有啊，有些人可能想写个比官方主插件更牛B的主插件2333

**Comment by harrynull** [comment]
对了，要不要弄个在线生成插件的服务……生成各种版本的插件(mingw,g++,clang,msvc)(x86/x64)(client/server)

**Comment by bridgekat** [comment]
有VPS就弄呗

**Comment by harrynull** [comment]
(╯‵□′)╯︵┻━┻他这么牛逼编译一个插件会死啊2333333333

**Comment by bridgekat** [comment]
人家牛B到嫌主插件编译太慢2333

**Comment by bridgekat** [comment]
对了，在线生成插件会不会被人当CI用233333333

**Comment by harrynull** [comment]
QAQ本来就是CI啊……
等等，那可以直接用appveyor生成啊23333333333333让别人发PR
（硬生生把Github弄成IM233333）

**Comment by bridgekat** [comment]
`NEWorld Plugin CI`
【GitHub本来就是IM

**Comment by harrynull** [comment]
其实是可行的吧，专门弄个repo，配置下appveyor，appveyor还自带打包下载功能233
就是不知道算不算abuse

**Comment by bridgekat** [comment]
什么abuse QAQ

**Comment by harrynull** [comment]
滥用CI

**Comment by bridgekat** [comment]
23333

**Comment by ascchrvalstr** [comment]
我记得有个什么gitter是专门给你们聊天的

**Comment by Miigon** [comment]
都用了CMake了还用什么shell script？
CMake现在的写法是我偷懒的，但是按照正确的分文件的方法生成出来的目标文件有和源文件一样的目录结构
比如：

```
bin/src/launcher/launcher
bin/src/shared/libshared.a
bin/src/client/libnwclient.so
```

你们来出个谋？

**Comment by amane-ame** [comment]
这不叫Bug，这叫特性

**Comment by DWVoid** [comment]
初步完成，准备整理CMake文件结构
