### ISSUE TITLE
服务端调用客户端插件会导致PluginApi用的是客户端的版本

### ISSUE THREAD

**Issue by harrynull** [Infinideastudio/NEWorld#77]
具体表现：启动服务器-添加方块-崩溃
原因：nwRegisterBlock调用的是NEWorld.dll的PluginAPI::Blocks，而这个值为nullptr(正常应该是调用NEWorldServer.dll的PluginAPI::Blocks)

**Comment by bridgekat** [comment]
nwapi.h里通过`#define NEWORLD_PLUGIN_CLIENT`和`#define NEWORLD_PLUGIN_SERVER`来区分客户端和服务端，如果没有define或者两个都define了就`#error`一下 233

**Comment by bridgekat** [comment]
然后C++版的插件，理论上客户端和服务端要分别配置附加依赖项为client.dll和server.dll
FB版插件直接在nwapi.h里用预处理器`#inclib`一下就好辣

**Comment by harrynull** [comment]
@qiaozhanrong 那就需要生成2~3个dll了啊
碎片化严重
有的东西是shared的，比如添加方块

**Comment by bridgekat** [comment]
插件dll只要生成2个啊，shared的东西是client.dll和server.dll里都有的辣

**Comment by harrynull** [comment]
@qiaozhanrong 写两份代码吗……还是引用同一个源码文件

**Comment by bridgekat** [comment]
插件也做个shared client server啊2333 然后编译出来也是俩dll

**Comment by harrynull** [comment]
@qiaozhanrong 好复杂的样子……那这样最好就给开发者提供个框架了

**Comment by bridgekat** [comment]
不同IDE框架不一样啊

**Comment by harrynull** [comment]
@qiaozhanrong 直接给CMakeLists.txt好了

**Comment by bridgekat** [comment]
额ok

**Comment by ascchrvalstr** [comment]
NEWorld Development Kit

**Comment by Miigon** [comment]
所以你们想通要用CMakeLists.txt来开发了？
说实话不喜欢VS Project，现在有大半commit是在维护那个文件，而CMakeLists.txt 除非引入新库否则没有修改的必要
shared是编译成静态库链接到server和client里的，所以shared里的符号客户端和服务端也会有

**Comment by harrynull** [comment]
@Miigon 没有，只是准备弄个插件开发模板(NDK)

**Comment by abc612008** [comment]
Fixed fa6a8a85601d470c73ec560b8c669b5f8eb30ad7

**Comment by harrynull** [comment]
Fixed
