### ISSUE TITLE
Gitter for NEWorld

### ISSUE THREAD

**Issue by Miigon** [Infinideastudio/NEWorld#79]
https://gitter.im/Infinideas-NEWorld/Lobby
不要再拿Github Issue当聊天工具了，不是很重要的，还有一些比较细节的需要充分讨论的东西，都去这里说吧
顺便，不要指望你们在QQ上说的东西我能知道，毕竟

```
Linux下没有QQ
Linux下没有QQ
Linux下没有QQ
```

**Comment by harrynull** [comment]
更加官方的gitter.im:
https://gitter.im/Infinideastudio/Lobby
已经添加到README 并且（随机）邀请了一部分人，请没收到邀请的人自己加入/互相邀请
