### ISSUE TITLE
Why do we need the "Foundation Kit"

### ISSUE THREAD

**Issue by bridgekat** [Infinideastudio/NEWorld#8]
Why don't put the "Foundation Kit" into NEWorld main project?

**Comment by DWVoid** [comment]
'Cause it'll be quite difficult if we try to call GUI or World classes through the ModAPI and it might cause some unnecessary problems. It's much easier to import these functions from a same dynamic library than passing all these function pointers to the mods by an callback function.

在 2016-03-22 19:47:07，qiaozhanrong notifications@github.com 写道：

Why don't put the "Foundation Kit" into NEWorld main project?

**Comment by DWVoid** [comment]
话说新创无际的百度号是什么？

在 2016-03-22 19:47:07，qiaozhanrong notifications@github.com 写道：

Why don't put the "Foundation Kit" into NEWorld main project?

**Comment by ghost** [comment]
@DREAMWORLDVOID 这个是什么情况啊，为什么NEWorldFoundationKit和NEWorld的代码完全重合了啊？如果这样，为什么不直接把NEWorld移动到FoundationKit里，然后NEWorld主程序变成一个FoundationKit的wrapper？

**Comment by DWVoid** [comment]
为了两组可以并行开发。这个FoundationKit估计初步成型就要一个半月，把其他人晾在一边也不是办法，就只能这样了，因为实际完工后文件结构会完全变掉

在 2016-03-22 21:54:00，"D Laboratory" notifications@github.com 写道：

@DREAMWORLDVOID 这个是什么情况啊，为什么NEWorldFoundationKit和NEWorld的代码完全重合了啊？如果这样，为什么不直接把NEWorld移动到FoundationKit里，然后NEWorld主程序变成一个FoundationKit的wrapper？

**Comment by ghost** [comment]
@DREAMWORLDVOID 并行开发...你直接拉一个分支不就行了...Git就是为了并行开发设计的...你这么搞就跟没有Git一个样子....又TM多了一坨垃圾文件

**Comment by jacky8399** [comment]
Email...excited

**Comment by DWVoid** [comment]
@DLaboratory 因为最初的一个工作失误。。。

**Comment by DWVoid** [comment]
这样把，我简单介绍一下FoundationKit的设计组成部分
1.NEWorldUserInterfaceKit(namespace NWUIK)
这部分是我现在正在构建的部分，基本包含所有的用户接口操作，并且完全实例化（受C#及WPF的影响比较大，最终的接口风格可能比较接近.Net
2.NEWorldWorldKit（namespace NEWDK）
NW世界核心
3.NetyCat
4.NNN

**Comment by bridgekat** [comment]
@DREAMWORLDVOID 给ModAPI做几个调用World/GUI的方法就是了。。。为什么要把代码复制一份。。。

**Comment by DWVoid** [comment]
不能用函数调用.这一工程的目的就是要完全实现OOP,然后你还要搞一堆函数…

发件人: noreply@github.com [mailto:noreply@github.com] 代表 qiaozhanrong
发送时间: 2016年3月22日 23:03
收件人: Infinideastudio/NEWorld NEWorld@noreply.github.com
抄送: DREAMWORLDVOID ys_37677@126.com
主题: Re: [NEWorld] Why do we need the "Foundation Kit" (#8)

@DREAMWORLDVOID https://github.com/DREAMWORLDVOID  给ModAPI做几个调用World/GUI的方法就是了。。。为什么要把代码复制一份。。。

**Comment by bridgekat** [comment]
@DREAMWORLDVOID 
你搞错了，NW内部代码是OOP，但是对Mod的接口可以用函数
而且Mod接口原先的设计是Mod DLL提供回调函数让主程序调用

**Comment by DWVoid** [comment]
然而这样反而麻烦。你可以看看我新写的GUI的Control类。里面所有的操作都依靠Class完成。这样的话就意味着你需要在GUI中通过句柄来实现操作（一个我最想避免的东西，因为编写及其困难），一这样就莫名其妙多出来了一堆函数（至少几十个），而且效率会急剧下降。我说的麻烦就在这里，因为接下来每个类都会是这样。通过dll实现能够最大程度地降低代码的复杂度，并且增加函数复用率。

发件人: bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com [mailto:bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com] 代表 qiaozhanrong
发送时间: 2016年3月23日 15:21
收件人: Infinideastudio/NEWorld NEWorld@noreply.github.com
抄送: DREAMWORLDVOID ys_37677@126.com
主题: Re: [NEWorld] Why do we need the "Foundation Kit" (#8)

@DREAMWORLDVOID https://github.com/DREAMWORLDVOID  你搞错了，NW内部代码是OOP，但是对Mod的接口可以用函数

**Comment by jacky8399** [comment]
直接搞個interface...然後
不對 你們C++不是直接NEWorld.h的嗎

**Comment by jacky8399** [comment]
(一臉茫然)
Java大法好

**Comment by taxerap** [comment]
exciting

**Comment by DWVoid** [comment]
基本是这个意思，只不过名字不一样

发件人: noreply@github.com [mailto:noreply@github.com] 代表 0u0
发送时间: 2016年3月23日 18:58
收件人: Infinideastudio/NEWorld NEWorld@noreply.github.com
抄送: DREAMWORLDVOID ys_37677@126.com
主题: Re: [NEWorld] Why do we need the "Foundation Kit" (#8)

直接搞個interface...然後
不對 你們C++不是直接NEWorld.h的嗎

**Comment by ascchrvalstr** [comment]
个人建议搞一个ModSDK之类的动态库，封装一些全局功能，然后导出函数。

**Comment by SuperSodaSea** [comment]
@DREAMWORLDVOID 
Netycat已经坑了……

**Comment by jacky8399** [comment]
捕捉野生bobby825
![b8zgbs gpegko6z96b5 h6](https://cloud.githubusercontent.com/assets/7542810/14078598/a2551812-f529-11e5-9284-bbcae28a61d2.jpg)

**Comment by ascchrvalstr** [comment]
看看我新写的Plugin SDK，不知道比你们写的高到哪里去了

**Comment by DWVoid** [comment]
我是打算完全重写NW的构架，因为需要插件版本管理，可扩展性，与兼容性检查

发件人: bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com [mailto:bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com] 代表 Bruce Dai
发送时间: 2016年4月4日 0:44
收件人: Infinideastudio/NEWorld NEWorld@noreply.github.com
抄送: DREAMWORLDVOID ys_37677@126.com
主题: Re: [Infinideastudio/NEWorld] Why do we need the "Foundation Kit" (#8)

看看我新写的Plugin SDK，不知道比你们写的高到哪里去了

**Comment by ascchrvalstr** [comment]
NEWorldFoundationKit has been deleted.
