### ISSUE TITLE
完善64位支持

### ISSUE THREAD

**Issue by harrynull** [Infinideastudio/NEWorld#81]
现在NEWorld已经可以在64位上编译
但是还需要完善插件/联机方面的64位支持

希望大家一起统一一个规范（例如统一接口等）

64位支持的重难点，以及必要性等

**Comment by Miigon** [comment]
本来就可以在64位上编译
我调试都是编译64位的
插件区分位数。

**Comment by DWVoid** [comment]
本来就可以。唯一的问题是依赖库制作的时候的位数，但是这个取决于开发者

**Comment by Miigon** [comment]
还是扯到了插件的问题了
看来要力推NWLua了

**Comment by DWVoid** [comment]
这么说我还得为UI提供lua接口？

**Comment by Miigon** [comment]
不需要，但需要一个C接口

**Comment by harrynull** [comment]
脚本语言的效率……想想看每tick都要执行好几十遍的世界生成器（这玩意在重写前CPU占用一小半）是脚本语言写的……233

**Comment by Miigon** [comment]
@abc612008 解释语言的效率当然低，但是如果是即时编译语言的话，除了过于极端的优化不能做之外，效率≈编译语言，函数调用有时更快
每tick执行好几十遍什么鬼。难道执行一次生成一个方块？

**Comment by Miigon** [comment]
Luajit和V8的效率应该不用说了吧？都见过cocos2d-x吧

**Comment by DWVoid** [comment]
@Miigon 提供C接口目前看来有难度。如果需要脚本的话最好指定一个脚本语言和执行器，直接注入代码，否则内存效率和执行效率都不行

**Comment by Miigon** [comment]
@DREAMWORLDVOID 实际上指定一个脚本语言和直接绑定C接口的难度是差不多的，甚至更大，而后者更通用
效率的话不用担心，Luajit的CFunction调用被执行后直接调用C函数的开销和在C内调用的开销一样（都是汇编级别的调用），我们只需在把这个调用转换到对应的C接口就好了，也就是加一层封装。
如果不提供C接口的话，将会导致不同编译器的接口名称不同，插件将需要提供针对不同编译器的多个版本。

退一步讲，就算如你所说指定一个脚本语言和执行器，也不代表不需要C接口了，常用的脚本语言如CPython(pypy),Lua(jit)都是由C编写的，绑定只能是C函数或静态类函数，“类”的概念也是只有存在于其自身语言，并无法把C++类_直接_绑定到其中，就算是使用C++编写的V8，也无法这么做。
_直接注入代码，并不意味着不需要做这种从`C++类`到`Lua类`或者`Python类`的转换，而是会把问题加剧_

如果这些各位都理解的话，那就好说了。
当然有极端方案，那就是内嵌脚本语言，使用tolua++之类的工具让工具来帮我们完成“从`C++类`到`Lua类`或者`Python类`的转换”，但是这就和`扩展性`的本意相违了。

**Comment by harrynull** [comment]
坚决反对脚本语言用在效率瓶颈处

**Comment by Miigon** [comment]
又没说要用在瓶颈处
又不是真有~~脑残~~用脚本语言写世界生成器

**Comment by harrynull** [comment]
不然咋写

**Comment by Miigon** [comment]
不是很简单的道理么？我只是在讨论`使用插件来支持Lua`而不是`只能用Lua`
再说就跑题了
正题，怎么解决指针跨位数的问题

**Comment by harrynull** [comment]
使用插件可以啊，弄个Lua插件，游戏做大了我们不弄也会有别人帮我们弄的
指针跨位数……那就32位用32位插件64位用64位插件啊

**Comment by ascchrvalstr** [comment]
lua不大喜欢，PyPy是吼的
