### ISSUE TITLE
用rapidjson代替NNN

### ISSUE THREAD

**Issue by rand-fly** [Infinideastudio/NEWorld#9]
有现成的干嘛不用。。。而且rapidjson效率比NNN高多了(我做了不完全测试)

**Comment by bridgekat** [comment]
我就笑看

**Comment by DWVoid** [comment]
随便,只要用C++容易操作就行

发件人: bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com [mailto:bounces+848413-4ef4-ys_37677=126.com@sgmail.github.com] 代表 qiaozhanrong
发送时间: 2016年3月23日 21:36
收件人: Infinideastudio/NEWorld NEWorld@noreply.github.com
主题: Re: [NEWorld] 用rapidjson代替NNN (#9)

我就笑看

**Comment by ascchrvalstr** [comment]
我就笑看，反正我直接用现成的wxConfig

**Comment by SuperSodaSea** [comment]
感觉需要进行数据到文本转换再存不会比直接存二进制数据快吧……？
请求Benchmark

**Comment by rand-fly** [comment]
rapidjson内部就是用二进制的，只有要转换的时候才会转化成json文本

**Comment by DWVoid** [comment]
别吵了，我在构思一个新的动态存储架构，到时候准备代替NNN

在 2016-03-28 18:19:11，renfei147 notifications@github.com 写道：
rapidjson内部就是用二进制的，只有要转换的时候才会转化成json文本

发自我的 iPad

在 2016年3月28日，17:57，SuperSodaSea <notifications@github.com<mailto:notifications@github.com>> 写道：

感觉需要进行数据到文本转换再存不会比直接存二进制数据快吧……？
请求Benchmark

―

**Comment by ascchrvalstr** [comment]
垃圾NNN，毁我青春

**Comment by ascchrvalstr** [comment]
NNN已删
