### ISSUE TITLE
关于ChunkRenderer重构的思路

### ISSUE THREAD

**Issue by bridgekat** [Infinideastudio/NEWorld#91]
众所周知，一个ChunkRenderer要对应上一个Chunk（要存储每个Chunk的VBO ID等渲染数据），这样在Client里还要写个ChunkRenderer的管理，和对Chunk的管理方式一模一样。写两遍明显是作死的行为，所以我就打算做一些调整。。。
由于ChunkRenderer相当于是对Chunk的扩展，可以想到让ChunkRenderer继承Chunk，Client在World中存储的Chunk*实际上指向ChunkRenderer。这样Client在向World里插入new Chunk时实际上要new ChunkRenderer，World的addChunk()在Client和Server里就是不同的。这个“不同”的处理方式，可以是**让WorldRenderer继承World，然后用虚函数那一套搞一下**；也可以是按照@abc612008 的想法，**在Client和Server里放不同的函数实现**；也可以想到**在World上用模板**，但是我并不清楚模板类的成员函数是不是要放到头文件里，可能为了优雅还要加一堆concept check。。。
或者还有一些思路。。。比如可以不编译Shared，**直接把Shared的代码同时作为Client和Server的一部分**，这样Shared中可以通过#ifdef来区分Client和Server的代码，自由度更高，但可能会增加编译时间。。。还可以**在Chunk里加个void*的指针，存储Client和Server对Chunk的附加数据**。。。
所以作为一个选择困难症患者，我应该用那种方法呢。。。

**Comment by harrynull** [comment]
感觉都不错啊……也没啥明显的利弊……
个人倾向：前两个方案>第四个方案>第三个方案(编译慢，不便于管理代码，代码混乱(全都写在一起了))

**Comment by bridgekat** [comment]
一共有5个方案。。。
我比较倾向编译慢的那个方案（自由度高），其次是加指针和继承。。。
其实我问这个问题是怕我随便选了一种方案然后被意见不合的人批判一番23333

**Comment by harrynull** [comment]
最后一个方案明显不太好
1. 编译慢
2. 不便于管理代码（VS中客户端服务端要分别加文件，容易遗漏）
前两个都无所谓的话……
3. 代码混乱，一个chunk类里一会客户端一会服务端，各种宏交错在一起

**Comment by bridgekat** [comment]
不会交错太多的，Chunk里顶多就是

``` C++
#ifdef NEWORLD_CLIENT
    bool vertexArrayBuilt = false;
    VertexBufferID vb[3];
#endif
```

函数啥的还是写到ChunkRenderer ChunkLoader里

**Comment by bridgekat** [comment]
算了。。。我先试试用继承吧

**Comment by Miigon** [comment]
> 直接把Shared的代码同时作为Client和Server的一部分

wtf?拒绝！shared要是不作为static library的话又会写出一大堆乱七八糟的东西
先说结论：**_完成同一件事情的函数在client和server如果需要不同的行为的话应该在两端分别有一个同名函数**_
把他们放在shared里并用宏来区分？看似完美的同时弄出了所谓的“自由度”和“复用性”，实际上这里的“自由”只是偷懒的代名词罢了。

退一步讲，如果真的如你所说，将shared作为客户端和服务端的一部分去编译的话，那shared还有什么存在的意义呢？为什么不把这部分代码直接移动到客户端和服务端中呢？
如果这是三个互相独立类，你现在就好比你提议想要他们互相成为friend类，理由是这样容易访问

**Comment by Miigon** [comment]
继承并不能解决问题
`代码是写给人看的`
那么，请 @qiaozhanrong 同学用自然语言解释一下，`保存区块渲染信息的类`和`保存区块方块与实体的类`之间的关系？

并且这种指针引用可能会导致不安全

**Comment by harrynull** [comment]
@Miigon 其实是你理解错了，之前的设计只是无奈罢了
现在的ClientChunk和Chunk(Shared)的关系的确是继承最好，“客户端的区块”继承"普通区块"
is-a测试：客户端的区块是一种普通区块√
客户端区块只是在原来的区块基础上扩展了渲染函数和相关的field，相当于普通区块+渲染功能，不用继承用啥？

**Comment by Miigon** [comment]
原来的名字叫ChunkRenderer也是醉了

**Comment by bridgekat** [comment]
原来没想到要扩展成员变量
