### ISSUE TITLE
文档的后缀名错误和用词不准确

### ISSUE THREAD

**Issue by huixiong806** [Infinideastudio/NEWorld#92]
编译指南中有一行
2.下载dependencies.exe,解压到./
......
还有一行
配制方法和32位雷同，...........
雷同，指随声附和，与他人的一样；也指一些事物不该相同而相同。

**Comment by harrynull** [comment]
后缀名对的，就是exe

**Comment by harrynull** [comment]
“雷同”已修改，感谢0w0
