### ISSUE TITLE
合并配置文件

### ISSUE THREAD

**Issue by harrynull** [Infinideastudio/NEWorld#93]
配置文件应想办法合并为一个，否则会导致部分设置项多次出现

**Comment by Miigon** [comment]
支持，并且插件是不是最好能做到客户端和服务端使用同一个？这样可以吧插件放在同个目录里，才不用一个插件区分两个版本

**Comment by Miigon** [comment]
比如在getInfo的时候给个参数表示加载本插件的是客户端还是服务端
