### ISSUE TITLE
项目仍需结构性调整

### ISSUE THREAD

**Issue by DWVoid** [Infinideastudio/NEWorld#96]
目前的NW项目线程调用错综复杂，锁竞争严重，还有各种dll锁导致的死锁问题以及一堆abort（）导致没法调试的情况。当前的结构并不是非常适合于某些东西的编写。故如题，我们可能需要一次结构调整。
主要计划如下：
合并服务端与客户端插件（减少dll数量），但是提供外壳插件API（比如小地图，GUI等）
改变服务端/客户端的项目划分为核心/外壳的划分
ChunkClient不再继承于Chunk而是改为保存Chunk指针（以避免不必要的copy）
目标主要是：
避免库的循环引用，减少线程并方便某些功能的编写

现征求意见

**Comment by bridgekat** [comment]
`ChunkClient`保存`Chunk`指针是很难做的，因为你要再开个跟`World`差不多的东西管理所有`ChunkClient`。。。
另外，我打算在单机的时候将世界更新等加入客户端，单机时不需要服务端，这个改动预计将在`ducai`分支完成。。。

**Comment by harrynull** [comment]
"ChunkClient保存Chunk指针是很难做的"并不难

**Comment by bridgekat** [comment]
你的意思是World里直接保存ChunkClient？

**Comment by harrynull** [comment]
存chunkmerged, which 继承chunkclient和chunkserver, which 都继承 chunk(base)

**Comment by bridgekat** [comment]
他说ChunkClient“不再继承于”Chunk

**Comment by DWVoid** [comment]
@qiaozhanrong 不用上ducai分支了，直接上renew吧

**Comment by DWVoid** [comment]
再统一一下意见：chunkclient继承chunk（含server部分）。是这样吧

**Comment by Miigon** [comment]
@qiaozhanrong 世界更新等加入客户端是错的
这样单机要怎么用属于server插件的功能？
最好还是使用跨线程通讯或者同线程内直接调用通讯
另：flatbuffer的构造和解析并不比struct慢多少，而如果拆分开来传递成参数会更慢

**Comment by harrynull** [comment]
我的意见和@miigon 的一样，这样搞感觉会很乱，而且有可能会导致单人游戏多人游戏的体验不一致

**Comment by DWVoid** [comment]
同意 @miigon 但是我赞同将服务端和客户端打包在一个二进制文件内

**Comment by Miigon** [comment]
@DREAMWORLDVOID 打包一个二进制内怎么实现？
符号可能会冲突

**Comment by ascchrvalstr** [comment]
总感觉你们在不停地新增代码文件，建议合并代码文件。
