### ISSUE TITLE
能不能提供Linux下的自动配置脚本

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/NEWorld#98]
现在只提供Ubuntu系的脚本`.travis.yml`，Fedora上的软件包名还得自己google，配置一次至少要30分钟。

**Comment by harrynull** [comment]
你可以提供下fedora的包名啊，然后加到docs里

**Comment by ascchrvalstr** [comment]
`mesa-libGL-devel` `mesa-libGLU-devel` `freeglut-devel`

**Comment by Miigon** [comment]
自动配置也不能保证包都能自己找到啊，最主要还是docs和manual

**Comment by harrynull** [comment]
@ascchrvalstr 实际上我们现在并没用到freeglut...

**Comment by DWVoid** [comment]
像Ubuntu的话主要依赖apt，我不知道fedora的包管理叫什么，但是一般来说配置用不了三十分钟

**Comment by ascchrvalstr** [comment]
DNF

**Comment by Miigon** [comment]
@DREAMWORLDVOID fedora似乎没有太过完整的包管理
